## Install Dependencies

In [1]:
# Dependencis for the notebook
%pip install spacy pandas torch transformers huggingface_hub matplotlib ipympl rdflib sentence_transformers numpy
# optuna and optional dependencies
%pip install optuna scikit-learn plotly 
# Qwen optimization (optional) dependencies
%pip install flash-linear-attention causal-conv1d
# Mistral dependencies
%pip install accelerate

/home/rpatroni/bzk-post-processing/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
/home/rpatroni/bzk-post-processing/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
/home/rpatroni/bzk-post-processing/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.
/home/rpatroni/bzk-post-processing/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import matplotlib.pyplot as plt
import matplotlib
import optuna.visualization
import optuna.importance
import json
from pathlib import Path
from collections import OrderedDict
from modules.llms import (
    JSONTuplesPromptTemplate,
    JsonDictPromptTemplate,
    PromptTemplate,
    LLMAddressParsingModel,
    QwenAddressParsingModel,
    ZeroShot,
    SimilarExamples,
    FixedExamples,
    NERPatternSimilarExamples,
    FallbackExamplesStrategy,
    HybridSimilarExamples,
    FIXED_DEMO_EXAMPLES
)
from modules.deepparse_parser import DeepParseParser
from modules.libpostal_client import LibpostalClient
from modules.utils import compare_preds, format_time, natural_casing
from typing import NamedTuple
from tqdm.auto import tqdm

import abc
import pandas as pd
import time
import pprint
import textwrap
import numpy as np
import modules.train_ner as train_ner

# Total number of addresses in the complete BZK data for calculating estimated time of processing
TOTAL_ADDRESSES = 4_394_539

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:1007: UserWarning: Can't initialize NVML
  raw_cnt = _raw_device_count_nvml()

## Set hardware accelerator

In [3]:
# List available hardware accelerators for PyTorch
import torch
available_accelerators = []
if torch.cuda.is_available():
    print("CUDA - available devices:")
    for i in range(torch.cuda.device_count()):
        print(f"  {i}: {torch.cuda.get_device_name(i)}")
        available_accelerators.append(torch.device(f'cuda:{i}'))
elif torch.accelerator.is_available(): # Support other hardware accelators
    available_accelerators.append(torch.accelerator.current_accelerator())
else:
    print("WARNING: Running on CPU")
    device = torch.device('cpu')

CUDA - available devices:
  0: NVIDIA A100 80GB PCIe

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:1007: UserWarning: Can't initialize NVML
  raw_cnt = _raw_device_count_nvml()

In [4]:
if available_accelerators:
    device = available_accelerators[0]
print(f"Torch version: {torch.__version__}, Device: {device}")

Torch version: 2.10.0+cu128, Device: cuda:0

## Load Dataset

Read all splits and concat them

In [5]:
csv_read_args = dict(keep_default_na=False, dtype=str, na_values=[""])

bzkopen_train = pd.read_csv("open_data/bzkopen_addresses_train.csv", **csv_read_args)
bzkopen_val = pd.read_csv("open_data/bzkopen_addresses_val.csv", **csv_read_args)
bzkopen_test = pd.read_csv("open_data/bzkopen_addresses_val.csv", **csv_read_args)
bzkopen_merged : pd.DataFrame = pd.concat(
    [bzkopen_train, bzkopen_val, bzkopen_test], 
    keys=['train', 'val', 'test'], 
    names=['split', 'row']
)
display(bzkopen_merged.sample(5))

                             field                           FullAddress  \
split row
train 658  ApplicantCurrentAddress    2434 e Ave. Cedar Rapids, Iowa/USA
      355      ApplicantBirthPlace                      Rostoko/Bukowina
      36       ApplicantBirthPlace                        Aschbach/Pfalz
      113  ApplicantCurrentAddress  Eitorf, Bahnhofstr. 35 Reg.Bez. Köln
      25          VictimDeathPlace                  Auschwitz umgekommen

          UnitNumber HouseNumber   StreetName Neighborhood          City  \
split row
train 658        NaN        2434       e Ave.          NaN  Cedar Rapids
      355        NaN         NaN          NaN          NaN       Rostoko
      36         NaN         NaN          NaN          NaN      Aschbach
      113        NaN          35  Bahnhofstr.          NaN        Eitorf
      25         NaN         NaN          NaN          NaN           NaN

          District    Region State Country PostalCode
split row
train 658      NaN       NaN  Iowa     USA        NaN
      355      NaN  Bukowina   NaN     NaN        NaN
      36       NaN     Pfalz   NaN     NaN        NaN
      113     Köln       NaN   NaN     NaN        NaN
      25       NaN       NaN   NaN     NaN        NaN

## Create folds

In [6]:
N_FOLDS = 10

# Set shuffle seed for reproducibility
SEED=4841762

In [7]:
# Define paths for saving models and predictions
models_path = Path("models") / "cross_val" / f"{N_FOLDS}_folds" / f"seed_{SEED}"
models_path.mkdir(parents=True, exist_ok=True)
preds_path = Path("experiments_data") / "cross_val" / f"{N_FOLDS}_folds" / f"seed_{SEED}"
preds_path.mkdir(parents=True, exist_ok=True)

In [8]:
class Fold(NamedTuple):
    fold_idx: int
    train_data: pd.DataFrame
    val_data: pd.DataFrame
    models_path: Path
    preds_path: Path

In [9]:

shuffled_bzkopen = bzkopen_merged.sample(frac=1, random_state=SEED)

fold_indices = np.array_split(shuffled_bzkopen.index, N_FOLDS)

folds = []

for fold_idx, val_indices in enumerate(fold_indices):
    train_indices = shuffled_bzkopen.index.difference(val_indices)
    fold_models_path = models_path / f"fold_{fold_idx}"
    fold_models_path.mkdir(parents=True, exist_ok=True)
    fold_preds_path = preds_path / f"fold_{fold_idx}"
    fold_preds_path.mkdir(parents=True, exist_ok=True)
    folds.append(Fold(
        fold_idx, 
        shuffled_bzkopen.loc[train_indices], 
        shuffled_bzkopen.loc[val_indices],
        fold_models_path, 
        fold_preds_path
    ))
display(pd.DataFrame([[len(x) for x in [fold.val_data, fold.train_data]] for fold in folds], columns=['val_fold_size', 'train_fold_size']))

   val_fold_size  train_fold_size
0            108              967
1            108              967
2            108              967
3            108              967
4            108              967
5            107              968
6            107              968
7            107              968
8            107              968
9            107              968

# Train Spacy NER models

These models are used for the pattern example matching strategy so they will be reused over multiple different experiments. Therefore it is useful to train them in advance.

In [10]:
for fold in tqdm(folds, unit="fold"):
    train_ner.train(
        n_iter=30,
        output_dir=fold.models_path / 'ner_bzk',
        train_df=fold.train_data,
        val_df=fold.val_data
    )

  0%|          | 0/10 [00:00<?, ?fold/s]

Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 967 rows
  934 examples (provided train) (33 skipped, 10 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 108 rows
  105 examples (provided val) (3 skipped, 0 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wehr/Baden, Enkendorfstr. 15." with entities "[(0, 4, 'City'), (12, 25, 'StreetName'), (26, 28, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen, Klitzenburg7(Gröp.)" with entities "[(0, 6, 'City'), (8, 19, 'StreetName'), (19, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochest N.Y./USA., 1441 Monroe Avenue" with entities "[(0, 7, 'City'), (8, 12, 'State'), (13, 16, 'Count...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Giwattaim, Sohun. Rosenstein Nr.32" with entities "[(0, 9, 'City'), (18, 28, 'StreetName'), (32, 34, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wuppertal-Sudberg, Hintersudberg 27 Reg.Bez. Düsse..." with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (19, 32...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main, Sellerstr.30/Frankfurt/Main (Hesse..." with entities "[(0, 14, 'City'), (16, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rixdorf (Berlin-Neuköln)" with entities "[(9, 15, 'City'), (16, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Tel Aviv/Israel. Javnestr: 16." with entities "[(0, 8, 'City'), (9, 15, 'Country'), (17, 25, 'Str...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankenthal Konrad-Linkstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "St. Johann-Saarbrücken" with entities "[(0, 10, 'Neighborhood'), (11, 22, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochester, N.Y./USA., 300 Joseph Ave." with entities "[(0, 9, 'City'), (11, 15, 'State'), (16, 20, 'Coun...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main-Fechenheim" with entities "[(0, 14, 'City'), (15, 25, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Dortmund-Lütgendortmund" with entities "[(0, 8, 'City'), (9, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text " <UNK> Ffm.-Höchst, Gartenstrasse 7" with entities "[(7, 11, 'City'), (12, 18, 'Neighborhood'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Strafanstalt Straubing Äussere Passauerstr.26" with entities "[(13, 22, 'City'), (23, 43, 'StreetName'), (43, 45...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1942.61  P=0.6181  R=0.6738  F1=0.6448 *
  iter   2  loss= 1151.13  P=0.7604  R=0.7082  F1=0.7333 *
  iter   3  loss=  866.44  P=0.7904  R=0.7768  F1=0.7835 *
  iter   4  loss=  719.33  P=0.7839  R=0.7940  F1=0.7889 *
  iter   5  loss=  567.45  P=0.7815  R=0.7983  F1=0.7898 *
  iter   6  loss=  516.53  P=0.7890  R=0.8026  F1=0.7957 *
  iter   7  loss=  416.14  P=0.8077  R=0.8112  F1=0.8094 *
  iter   8  loss=  368.14  P=0.8109  R=0.8283  F1=0.8195 *
  iter   9  loss=  328.18  P=0.8216  R=0.8498  F1=0.8354 *
  iter  10  loss=  284.58  P=0.8051  R=0.8155  F1=0.8102
  iter  11  loss=  269.92  P=0.8276  R=0.8240  F1=0.8258
  iter  12  loss=  191.49  P=0.8085  R=0.8155  F1=0.8120
  iter  13  loss=  175.66  P=0.8197  R=0.8197  F1=0.8197
  iter  14  loss=  184.30  P=0.8151  R=0.8326  F1=0.8238
  iter  15  loss=  166.99  P=0.8125  R=0.8369  F1=0.8245
  iter  16  loss=  126.78  P=0.8133  R=0.8412  F1=0.8270
  iter  17  loss=  149.90  P=0.8426  R=0.8498  F1=0.8462 *
  iter  18  loss=  139.08  P=0.8326  R=0.8541  F1=0.8432
  iter  19  loss=  105.36  P=0.8298  R=0.8369  F1=0.8333
  iter  20  loss=  119.58  P=0.8091  R=0.8369  F1=0.8228
  iter  21  loss=  114.22  P=0.8125  R=0.8369  F1=0.8245
  iter  22  loss=  119.82  P=0.8250  R=0.8498  F1=0.8372
  iter  23  loss=  106.08  P=0.8419  R=0.8455  F1=0.8437
  iter  24  loss=   90.15  P=0.8426  R=0.8498  F1=0.8462
  iter  25  loss=  120.62  P=0.8455  R=0.8455  F1=0.8455
  iter  26  loss=   89.27  P=0.8546  R=0.8326  F1=0.8435
  iter  27  loss=   75.55  P=0.8498  R=0.8498  F1=0.8498 *
  iter  28  loss=   83.16  P=0.8326  R=0.8326  F1=0.8326
  iter  29  loss=   74.65  P=0.8390  R=0.8498  F1=0.8443
  iter  30  loss=   55.30  P=0.8340  R=0.8412  F1=0.8376

Best val F1: 0.8498 — model saved to models/cross_val/10_folds/seed_4841762/fold_0/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 967 rows
  936 examples (provided train) (31 skipped, 9 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 108 rows
  103 examples (provided val) (5 skipped, 1 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Giwattaim, Sohun. Rosenstein Nr.32" with entities "[(0, 9, 'City'), (18, 28, 'StreetName'), (32, 34, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "St. Johann-Saarbrücken" with entities "[(0, 10, 'Neighborhood'), (11, 22, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "München 15, Herzog Heinrichstr.30/III" with entities "[(0, 7, 'City'), (12, 31, 'StreetName'), (31, 33, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text " <UNK> Ffm.-Höchst, Gartenstrasse 7" with entities "[(7, 11, 'City'), (12, 18, 'Neighborhood'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hagen-Haspe" with entities "[(0, 5, 'City'), (6, 11, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Marstetten-Aitrach, Kr. Wangen" with entities "[(0, 10, 'Neighborhood'), (11, 18, 'City'), (24, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankenthal Konrad-Linkstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wehr/Baden, Enkendorfstr. 15." with entities "[(0, 4, 'City'), (12, 25, 'StreetName'), (26, 28, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Solingen-Wald, Stübbenerstr. 4" with entities "[(0, 8, 'City'), (9, 13, 'Neighborhood'), (15, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Freiburg/Br., Günterstalstr. 54." with entities "[(0, 8, 'City'), (9, 12, 'State'), (14, 28, 'Stree...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Gonsenheim Eleonorenstr. 34" with entities "[(0, 5, 'City'), (6, 16, 'Neighborhood'), (17, 30,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Offenbach/MainBieber, Seligenstädterstr.18 1/10" with entities "[(0, 9, 'City'), (14, 20, 'Neighborhood'), (22, 40...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wuppertal-Sudberg, Hintersudberg 27 Reg.Bez. Düsse..." with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (19, 32...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hofheim T., Hölderlin-Str.4 Kreis Main-Taunus" with entities "[(0, 10, 'City'), (12, 26, 'StreetName'), (26, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.

  iter   1  loss= 1935.75  P=0.7018  R=0.6584  F1=0.6794 *
  iter   2  loss= 1121.37  P=0.7801  R=0.7737  F1=0.7769 *
  iter   3  loss=  858.50  P=0.7826  R=0.8148  F1=0.7984 *
  iter   4  loss=  699.18  P=0.8216  R=0.8148  F1=0.8182 *
  iter   5  loss=  648.40  P=0.8443  R=0.8477  F1=0.8460 *
  iter   6  loss=  490.27  P=0.8382  R=0.8313  F1=0.8347
  iter   7  loss=  466.48  P=0.8361  R=0.8395  F1=0.8378
  iter   8  loss=  407.15  P=0.8462  R=0.8601  F1=0.8531 *
  iter   9  loss=  381.53  P=0.8360  R=0.8601  F1=0.8479
  iter  10  loss=  310.06  P=0.8486  R=0.8765  F1=0.8623 *
  iter  11  loss=  265.90  P=0.8382  R=0.8313  F1=0.8347
  iter  12  loss=  206.97  P=0.8449  R=0.8519  F1=0.8484
  iter  13  loss=  214.67  P=0.8440  R=0.8683  F1=0.8560
  iter  14  loss=  194.97  P=0.8490  R=0.8560  F1=0.8525
  iter  15  loss=  158.26  P=0.8508  R=0.8683  F1=0.8595
  iter  16  loss=  161.16  P=0.8514  R=0.8724  F1=0.8618
  iter  17  loss=  152.61  P=0.8560  R=0.8560  F1=0.8560
  iter  18  loss=  134.31  P=0.8560  R=0.8560  F1=0.8560
  iter  19  loss=  130.66  P=0.8394  R=0.8601  F1=0.8496
  iter  20  loss=  129.80  P=0.8692  R=0.8477  F1=0.8583
  iter  21  loss=  124.22  P=0.8735  R=0.8807  F1=0.8770 *
  iter  22  loss=  141.28  P=0.8443  R=0.8477  F1=0.8460
  iter  23  loss=  125.57  P=0.8402  R=0.8436  F1=0.8419
  iter  24  loss=  100.57  P=0.8462  R=0.8601  F1=0.8531
  iter  25  loss=  110.49  P=0.8642  R=0.8642  F1=0.8642
  iter  26  loss=   97.50  P=0.8683  R=0.8683  F1=0.8683
  iter  27  loss=  106.45  P=0.8612  R=0.8683  F1=0.8648
  iter  28  loss=   90.30  P=0.8653  R=0.8724  F1=0.8689
  iter  29  loss=   77.96  P=0.8449  R=0.8519  F1=0.8484
  iter  30  loss=   78.77  P=0.8636  R=0.8601  F1=0.8619

Best val F1: 0.8770 — model saved to models/cross_val/10_folds/seed_4841762/fold_1/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 967 rows
  933 examples (provided train) (34 skipped, 9 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 108 rows
  106 examples (provided val) (2 skipped, 1 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Gräfelfing b.München, Hartnagelstr.1/I" with entities "[(0, 10, 'Neighborhood'), (13, 20, 'City'), (22, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochester, N.Y./USA., 300 Joseph Ave." with entities "[(0, 9, 'City'), (11, 15, 'State'), (16, 20, 'Coun...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wuppertal-Sudberg, Hintersudberg 27 Reg.Bez. Düsse..." with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (19, 32...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "121 Tappan Avenue Belleville 9 N.Y./Kreis USA" with entities "[(0, 3, 'HouseNumber'), (4, 17, 'StreetName'), (18...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg,39 Sierichstr. 153." with entities "[(0, 7, 'City'), (11, 21, 'StreetName'), (23, 26, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Marstetten-Aitrach, Kr. Wangen" with entities "[(0, 10, 'Neighborhood'), (11, 18, 'City'), (24, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main-Fechenheim" with entities "[(0, 14, 'City'), (15, 25, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text " <UNK> Ffm.-Höchst, Gartenstrasse 7" with entities "[(7, 11, 'City'), (12, 18, 'Neighborhood'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Tel Aviv/Israel. Javnestr: 16." with entities "[(0, 8, 'City'), (9, 15, 'Country'), (17, 25, 'Str...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main, Sellerstr.30/Frankfurt/Main (Hesse..." with entities "[(0, 14, 'City'), (16, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Solingen-Wald, Stübbenerstr. 4" with entities "[(0, 8, 'City'), (9, 13, 'Neighborhood'), (15, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Van Nuys-Los Angeles Calif., 13929 Chandler Bld. U..." with entities "[(0, 8, 'Neighborhood'), (9, 20, 'City'), (21, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hofheim T., Hölderlin-Str.4 Kreis Main-Taunus" with entities "[(0, 10, 'City'), (12, 26, 'StreetName'), (26, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wehr/Baden, Enkendorfstr. 15." with entities "[(0, 4, 'City'), (12, 25, 'StreetName'), (26, 28, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochest N.Y./USA., 1441 Monroe Avenue" with entities "[(0, 7, 'City'), (8, 12, 'State'), (13, 16, 'Count...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1992.76  P=0.6598  R=0.5818  F1=0.6184 *
  iter   2  loss= 1140.66  P=0.7689  R=0.7409  F1=0.7546 *
  iter   3  loss=  895.52  P=0.7662  R=0.8045  F1=0.7849 *
  iter   4  loss=  693.41  P=0.7763  R=0.8045  F1=0.7902 *
  iter   5  loss=  624.81  P=0.8100  R=0.8136  F1=0.8118 *
  iter   6  loss=  495.97  P=0.7937  R=0.8045  F1=0.7991
  iter   7  loss=  448.86  P=0.8318  R=0.8318  F1=0.8318 *
  iter   8  loss=  374.03  P=0.8186  R=0.8409  F1=0.8296
  iter   9  loss=  338.30  P=0.8591  R=0.8591  F1=0.8591 *
  iter  10  loss=  306.81  P=0.8333  R=0.8409  F1=0.8371
  iter  11  loss=  287.97  P=0.8259  R=0.8409  F1=0.8333
  iter  12  loss=  220.47  P=0.8349  R=0.8273  F1=0.8311
  iter  13  loss=  195.13  P=0.8645  R=0.8409  F1=0.8525
  iter  14  loss=  210.20  P=0.8525  R=0.8409  F1=0.8467
  iter  15  loss=  188.02  P=0.8423  R=0.8500  F1=0.8462
  iter  16  loss=  180.14  P=0.8378  R=0.8455  F1=0.8416
  iter  17  loss=  178.67  P=0.8170  R=0.8318  F1=0.8243
  iter  18  loss=  180.84  P=0.8426  R=0.8273  F1=0.8349
  iter  19  loss=  132.53  P=0.8380  R=0.8227  F1=0.8303
  iter  20  loss=  137.70  P=0.8738  R=0.8500  F1=0.8618 *
  iter  21  loss=   96.09  P=0.8512  R=0.8318  F1=0.8414
  iter  22  loss=  110.57  P=0.8426  R=0.8273  F1=0.8349
  iter  23  loss=  128.63  P=0.8273  R=0.8273  F1=0.8273
  iter  24  loss=  111.32  P=0.8318  R=0.8318  F1=0.8318
  iter  25  loss=  110.56  P=0.8611  R=0.8455  F1=0.8532
  iter  26  loss=   95.37  P=0.8664  R=0.8545  F1=0.8604
  iter  27  loss=   96.65  P=0.8493  R=0.8455  F1=0.8474
  iter  28  loss=   87.21  P=0.8525  R=0.8409  F1=0.8467
  iter  29  loss=   83.11  P=0.8402  R=0.8364  F1=0.8383
  iter  30  loss=   89.03  P=0.8394  R=0.8318  F1=0.8356

Best val F1: 0.8618 — model saved to models/cross_val/10_folds/seed_4841762/fold_2/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 967 rows
  938 examples (provided train) (29 skipped, 9 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 108 rows
  101 examples (provided val) (7 skipped, 1 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen-St. Magnus, Zum Fichtenhof 25" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochest N.Y./USA., 1441 Monroe Avenue" with entities "[(0, 7, 'City'), (8, 12, 'State'), (13, 16, 'Count...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Ingelheim-Mitte, Zuckerberg 23" with entities "[(0, 9, 'City'), (10, 15, 'Neighborhood'), (17, 27...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Marstetten-Aitrach, Kr. Wangen" with entities "[(0, 10, 'Neighborhood'), (11, 18, 'City'), (24, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg,39 Sierichstr. 153." with entities "[(0, 7, 'City'), (11, 21, 'StreetName'), (23, 26, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Solingen-Wald, Stübbenerstr. 4" with entities "[(0, 8, 'City'), (9, 13, 'Neighborhood'), (15, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Strafanstalt Straubing Äussere Passauerstr.26" with entities "[(13, 22, 'City'), (23, 43, 'StreetName'), (43, 45...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "München 15, Herzog Heinrichstr.30/III" with entities "[(0, 7, 'City'), (12, 31, 'StreetName'), (31, 33, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankenthal Konrad-Linkstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hagen-Haspe" with entities "[(0, 5, 'City'), (6, 11, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Gräfelfing b.München, Hartnagelstr.1/I" with entities "[(0, 10, 'Neighborhood'), (13, 20, 'City'), (22, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hofheim T., Hölderlin-Str.4 Kreis Main-Taunus" with entities "[(0, 10, 'City'), (12, 26, 'StreetName'), (26, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 2014.77  P=0.6682  R=0.6872  F1=0.6776 *
  iter   2  loss= 1166.74  P=0.7818  R=0.8152  F1=0.7981 *
  iter   3  loss=  885.91  P=0.7857  R=0.8341  F1=0.8092 *
  iter   4  loss=  734.93  P=0.8111  R=0.8341  F1=0.8224 *
  iter   5  loss=  580.51  P=0.8626  R=0.8626  F1=0.8626 *
  iter   6  loss=  525.80  P=0.8479  R=0.8720  F1=0.8598
  iter   7  loss=  421.71  P=0.8605  R=0.8768  F1=0.8685 *
  iter   8  loss=  376.66  P=0.8645  R=0.8768  F1=0.8706 *
  iter   9  loss=  344.97  P=0.8692  R=0.8815  F1=0.8753 *
  iter  10  loss=  298.80  P=0.8611  R=0.8815  F1=0.8712
  iter  11  loss=  252.64  P=0.8883  R=0.8673  F1=0.8777 *
  iter  12  loss=  239.20  P=0.8645  R=0.8768  F1=0.8706
  iter  13  loss=  203.36  P=0.8493  R=0.8815  F1=0.8651
  iter  14  loss=  198.27  P=0.8657  R=0.8863  F1=0.8759
  iter  15  loss=  185.29  P=0.8638  R=0.8720  F1=0.8679
  iter  16  loss=  169.82  P=0.8585  R=0.8626  F1=0.8605
  iter  17  loss=  161.86  P=0.8720  R=0.8720  F1=0.8720
  iter  18  loss=  144.28  P=0.8815  R=0.8815  F1=0.8815 *
  iter  19  loss=  141.79  P=0.8883  R=0.8673  F1=0.8777
  iter  20  loss=  117.39  P=0.8821  R=0.8863  F1=0.8842 *
  iter  21  loss=   99.69  P=0.8578  R=0.8863  F1=0.8718
  iter  22  loss=  120.91  P=0.8598  R=0.8720  F1=0.8659
  iter  23  loss=  127.46  P=0.8558  R=0.8720  F1=0.8638
  iter  24  loss=  100.85  P=0.8692  R=0.8815  F1=0.8753
  iter  25  loss=   92.69  P=0.8651  R=0.8815  F1=0.8732
  iter  26  loss=  101.59  P=0.8525  R=0.8768  F1=0.8645
  iter  27  loss=  107.71  P=0.8611  R=0.8815  F1=0.8712
  iter  28  loss=   97.95  P=0.8815  R=0.8815  F1=0.8815
  iter  29  loss=   85.83  P=0.8774  R=0.8815  F1=0.8794
  iter  30  loss=   77.02  P=0.8605  R=0.8768  F1=0.8685

Best val F1: 0.8842 — model saved to models/cross_val/10_folds/seed_4841762/fold_3/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 967 rows
  937 examples (provided train) (30 skipped, 10 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 108 rows
  102 examples (provided val) (6 skipped, 0 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Gräfelfing b.München, Hartnagelstr.1/I" with entities "[(0, 10, 'Neighborhood'), (13, 20, 'City'), (22, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Giwattaim, Sohun. Rosenstein Nr.32" with entities "[(0, 9, 'City'), (18, 28, 'StreetName'), (32, 34, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wehr/Baden, Enkendorfstr. 15." with entities "[(0, 4, 'City'), (12, 25, 'StreetName'), (26, 28, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Strafanstalt Straubing Äussere Passauerstr.26" with entities "[(13, 22, 'City'), (23, 43, 'StreetName'), (43, 45...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hagen-Haspe" with entities "[(0, 5, 'City'), (6, 11, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "München 15, Herzog Heinrichstr.30/III" with entities "[(0, 7, 'City'), (12, 31, 'StreetName'), (31, 33, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Dortmund-Lütgendortmund" with entities "[(0, 8, 'City'), (9, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochest N.Y./USA., 1441 Monroe Avenue" with entities "[(0, 7, 'City'), (8, 12, 'State'), (13, 16, 'Count...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hofheim T., Hölderlin-Str.4 Kreis Main-Taunus" with entities "[(0, 10, 'City'), (12, 26, 'StreetName'), (26, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "121 Tappan Avenue Belleville 9 N.Y./Kreis USA" with entities "[(0, 3, 'HouseNumber'), (4, 17, 'StreetName'), (18...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1988.18  P=0.7630  R=0.7000  F1=0.7302 *
  iter   2  loss= 1118.28  P=0.8108  R=0.7826  F1=0.7965 *
  iter   3  loss=  886.66  P=0.7908  R=0.8217  F1=0.8060 *
  iter   4  loss=  748.68  P=0.8500  R=0.8130  F1=0.8311 *
  iter   5  loss=  640.03  P=0.8151  R=0.8435  F1=0.8291
  iter   6  loss=  529.77  P=0.8468  R=0.8652  F1=0.8559 *
  iter   7  loss=  471.41  P=0.8745  R=0.8783  F1=0.8764 *
  iter   8  loss=  396.30  P=0.8615  R=0.8652  F1=0.8633
  iter   9  loss=  354.93  P=0.8836  R=0.8913  F1=0.8874 *
  iter  10  loss=  308.04  P=0.8841  R=0.8957  F1=0.8898 *
  iter  11  loss=  276.59  P=0.8798  R=0.8913  F1=0.8855
  iter  12  loss=  253.52  P=0.8884  R=0.9000  F1=0.8942 *
  iter  13  loss=  227.10  P=0.9075  R=0.8957  F1=0.9015 *
  iter  14  loss=  185.05  P=0.8922  R=0.9000  F1=0.8961
  iter  15  loss=  179.76  P=0.8686  R=0.8913  F1=0.8798
  iter  16  loss=  153.33  P=0.8724  R=0.9217  F1=0.8964
  iter  17  loss=  151.69  P=0.8692  R=0.8957  F1=0.8822
  iter  18  loss=  161.37  P=0.8824  R=0.9130  F1=0.8974
  iter  19  loss=  140.42  P=0.8836  R=0.8913  F1=0.8874
  iter  20  loss=  128.89  P=0.8644  R=0.8870  F1=0.8755
  iter  21  loss=  122.36  P=0.8879  R=0.8957  F1=0.8918
  iter  22  loss=   92.25  P=0.8884  R=0.9000  F1=0.8942
  iter  23  loss=  117.28  P=0.8936  R=0.9130  F1=0.9032 *
  iter  24  loss=   84.13  P=0.8761  R=0.8913  F1=0.8836
  iter  25  loss=  104.08  P=0.8922  R=0.9000  F1=0.8961
  iter  26  loss=  107.45  P=0.8961  R=0.9000  F1=0.8980
  iter  27  loss=   82.00  P=0.8841  R=0.8957  F1=0.8898
  iter  28  loss=   78.58  P=0.8697  R=0.9000  F1=0.8846
  iter  29  loss=  111.51  P=0.8879  R=0.8957  F1=0.8918
  iter  30  loss=   94.55  P=0.8798  R=0.8913  F1=0.8855

Best val F1: 0.9032 — model saved to models/cross_val/10_folds/seed_4841762/fold_4/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 968 rows
  937 examples (provided train) (31 skipped, 10 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 107 rows
  102 examples (provided val) (5 skipped, 0 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Ingelheim-Mitte, Zuckerberg 23" with entities "[(0, 9, 'City'), (10, 15, 'Neighborhood'), (17, 27...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main, Sellerstr.30/Frankfurt/Main (Hesse..." with entities "[(0, 14, 'City'), (16, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text " <UNK> Ffm.-Höchst, Gartenstrasse 7" with entities "[(7, 11, 'City'), (12, 18, 'Neighborhood'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Freiburg/Br., Günterstalstr. 54." with entities "[(0, 8, 'City'), (9, 12, 'State'), (14, 28, 'Stree...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Offenbach/MainBieber, Seligenstädterstr.18 1/10" with entities "[(0, 9, 'City'), (14, 20, 'Neighborhood'), (22, 40...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "121 Tappan Avenue Belleville 9 N.Y./Kreis USA" with entities "[(0, 3, 'HouseNumber'), (4, 17, 'StreetName'), (18...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Hermsdorf, Junostr. 7" with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 26,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rixdorf (Berlin-Neuköln)" with entities "[(9, 15, 'City'), (16, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen, Klitzenburg7(Gröp.)" with entities "[(0, 6, 'City'), (8, 19, 'StreetName'), (19, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Gonsenheim Eleonorenstr. 34" with entities "[(0, 5, 'City'), (6, 16, 'Neighborhood'), (17, 30,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wehr/Baden, Enkendorfstr. 15." with entities "[(0, 4, 'City'), (12, 25, 'StreetName'), (26, 28, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hagen-Haspe" with entities "[(0, 5, 'City'), (6, 11, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochester, N.Y./USA., 300 Joseph Ave." with entities "[(0, 9, 'City'), (11, 15, 'State'), (16, 20, 'Coun...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankenthal Konrad-Linkstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg,39 Sierichstr. 153." with entities "[(0, 7, 'City'), (11, 21, 'StreetName'), (23, 26, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1933.65  P=0.6568  R=0.6485  F1=0.6526 *
  iter   2  loss= 1104.75  P=0.7178  R=0.7238  F1=0.7208 *
  iter   3  loss=  830.22  P=0.7711  R=0.8033  F1=0.7869 *
  iter   4  loss=  703.20  P=0.7722  R=0.7657  F1=0.7689
  iter   5  loss=  585.76  P=0.7621  R=0.7908  F1=0.7762
  iter   6  loss=  510.60  P=0.8255  R=0.8117  F1=0.8186 *
  iter   7  loss=  439.46  P=0.8050  R=0.8117  F1=0.8083
  iter   8  loss=  406.22  P=0.7824  R=0.7824  F1=0.7824
  iter   9  loss=  354.26  P=0.7941  R=0.7908  F1=0.7925
  iter  10  loss=  305.99  P=0.7683  R=0.7908  F1=0.7794
  iter  11  loss=  303.44  P=0.8042  R=0.8075  F1=0.8058
  iter  12  loss=  245.31  P=0.8312  R=0.8033  F1=0.8170
  iter  13  loss=  267.10  P=0.8077  R=0.7908  F1=0.7992
  iter  14  loss=  209.36  P=0.8376  R=0.8201  F1=0.8288 *
  iter  15  loss=  158.16  P=0.7942  R=0.8075  F1=0.8008
  iter  16  loss=  191.16  P=0.8151  R=0.8117  F1=0.8134
  iter  17  loss=  131.44  P=0.8268  R=0.7992  F1=0.8128
  iter  18  loss=  157.10  P=0.8193  R=0.8159  F1=0.8176
  iter  19  loss=  136.26  P=0.7837  R=0.8033  F1=0.7934
  iter  20  loss=  119.70  P=0.8041  R=0.8243  F1=0.8140
  iter  21  loss=  104.75  P=0.8170  R=0.8033  F1=0.8101
  iter  22  loss=   86.63  P=0.8291  R=0.8117  F1=0.8203
  iter  23  loss=   90.55  P=0.8228  R=0.8159  F1=0.8193
  iter  24  loss=   87.23  P=0.8041  R=0.8243  F1=0.8140
  iter  25  loss=   92.04  P=0.8059  R=0.7992  F1=0.8025
  iter  26  loss=   77.24  P=0.8074  R=0.8243  F1=0.8157
  iter  27  loss=   95.68  P=0.8117  R=0.8117  F1=0.8117
  iter  28  loss=   91.36  P=0.8083  R=0.8117  F1=0.8100
  iter  29  loss=   86.77  P=0.8216  R=0.8285  F1=0.8250
  iter  30  loss=   87.80  P=0.8167  R=0.8201  F1=0.8184

Best val F1: 0.8288 — model saved to models/cross_val/10_folds/seed_4841762/fold_5/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 968 rows
  935 examples (provided train) (33 skipped, 9 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 107 rows
  104 examples (provided val) (3 skipped, 1 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wu.-Elberfeld, Ronsdorferstr. 380" with entities "[(0, 3, 'District'), (4, 13, 'City'), (15, 29, 'St...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen, Klitzenburg7(Gröp.)" with entities "[(0, 6, 'City'), (8, 19, 'StreetName'), (19, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "121 Tappan Avenue Belleville 9 N.Y./Kreis USA" with entities "[(0, 3, 'HouseNumber'), (4, 17, 'StreetName'), (18...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Gonsenheim Eleonorenstr. 34" with entities "[(0, 5, 'City'), (6, 16, 'Neighborhood'), (17, 30,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "St. Johann-Saarbrücken" with entities "[(0, 10, 'Neighborhood'), (11, 22, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Giwattaim, Sohun. Rosenstein Nr.32" with entities "[(0, 9, 'City'), (18, 28, 'StreetName'), (32, 34, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wuppertal-Sudberg, Hintersudberg 27 Reg.Bez. Düsse..." with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (19, 32...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main, Sellerstr.30/Frankfurt/Main (Hesse..." with entities "[(0, 14, 'City'), (16, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Ingelheim-Mitte, Zuckerberg 23" with entities "[(0, 9, 'City'), (10, 15, 'Neighborhood'), (17, 27...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Hermsdorf, Junostr. 7" with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 26,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen-St. Magnus, Zum Fichtenhof 25" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Van Nuys-Los Angeles Calif., 13929 Chandler Bld. U..." with entities "[(0, 8, 'Neighborhood'), (9, 20, 'City'), (21, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rixdorf (Berlin-Neuköln)" with entities "[(9, 15, 'City'), (16, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1975.07  P=0.7277  R=0.7243  F1=0.7260 *
  iter   2  loss= 1109.54  P=0.8146  R=0.7804  F1=0.7971 *
  iter   3  loss=  854.47  P=0.8578  R=0.8738  F1=0.8657 *
  iter   4  loss=  693.12  P=0.8768  R=0.8318  F1=0.8537
  iter   5  loss=  601.50  P=0.8910  R=0.8785  F1=0.8847 *
  iter   6  loss=  494.24  P=0.9183  R=0.8925  F1=0.9052 *
  iter   7  loss=  466.21  P=0.8832  R=0.8832  F1=0.8832
  iter   8  loss=  409.72  P=0.8995  R=0.8785  F1=0.8889
  iter   9  loss=  331.94  P=0.8630  R=0.8832  F1=0.8730
  iter  10  loss=  303.50  P=0.8630  R=0.8832  F1=0.8730
  iter  11  loss=  261.29  P=0.8905  R=0.8738  F1=0.8821
  iter  12  loss=  259.72  P=0.8981  R=0.8645  F1=0.8810
  iter  13  loss=  222.53  P=0.9028  R=0.9112  F1=0.9070 *
  iter  14  loss=  189.09  P=0.9112  R=0.9112  F1=0.9112 *
  iter  15  loss=  193.77  P=0.9091  R=0.8879  F1=0.8983
  iter  16  loss=  160.07  P=0.8853  R=0.9019  F1=0.8935
  iter  17  loss=  150.08  P=0.9151  R=0.9065  F1=0.9108
  iter  18  loss=  138.77  P=0.9179  R=0.8879  F1=0.9026
  iter  19  loss=  155.60  P=0.9187  R=0.8972  F1=0.9078
  iter  20  loss=  108.76  P=0.9242  R=0.9112  F1=0.9176 *
  iter  21  loss=  108.58  P=0.8972  R=0.8972  F1=0.8972
  iter  22  loss=  141.63  P=0.8925  R=0.8925  F1=0.8925
  iter  23  loss=  144.11  P=0.8821  R=0.8738  F1=0.8779
  iter  24  loss=   89.03  P=0.8962  R=0.8879  F1=0.8920
  iter  25  loss=   90.02  P=0.8972  R=0.8972  F1=0.8972
  iter  26  loss=   89.43  P=0.9014  R=0.8972  F1=0.8993
  iter  27  loss=   63.98  P=0.9220  R=0.8832  F1=0.9021
  iter  28  loss=   72.06  P=0.9147  R=0.9019  F1=0.9082
  iter  29  loss=   88.44  P=0.9163  R=0.9206  F1=0.9184 *
  iter  30  loss=   77.28  P=0.9100  R=0.8972  F1=0.9035

Best val F1: 0.9184 — model saved to models/cross_val/10_folds/seed_4841762/fold_6/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 968 rows
  935 examples (provided train) (33 skipped, 9 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 107 rows
  104 examples (provided val) (3 skipped, 1 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Hermsdorf, Junostr. 7" with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 26,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen-St. Magnus, Zum Fichtenhof 25" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Gonsenheim Eleonorenstr. 34" with entities "[(0, 5, 'City'), (6, 16, 'Neighborhood'), (17, 30,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Solingen-Wald, Stübbenerstr. 4" with entities "[(0, 8, 'City'), (9, 13, 'Neighborhood'), (15, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Offenbach/MainBieber, Seligenstädterstr.18 1/10" with entities "[(0, 9, 'City'), (14, 20, 'Neighborhood'), (22, 40...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Giwattaim, Sohun. Rosenstein Nr.32" with entities "[(0, 9, 'City'), (18, 28, 'StreetName'), (32, 34, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main-Fechenheim" with entities "[(0, 14, 'City'), (15, 25, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "St. Johann-Saarbrücken" with entities "[(0, 10, 'Neighborhood'), (11, 22, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Tel Aviv/Israel. Javnestr: 16." with entities "[(0, 8, 'City'), (9, 15, 'Country'), (17, 25, 'Str...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Terbetscha, Lemberg,(Oesterreich) Polen" with entities "[(0, 10, 'Neighborhood'), (12, 19, 'City'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Ingelheim-Mitte, Zuckerberg 23" with entities "[(0, 9, 'City'), (10, 15, 'Neighborhood'), (17, 27...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 2001.25  P=0.7220  R=0.7318  F1=0.7269 *
  iter   2  loss= 1136.96  P=0.7629  R=0.8045  F1=0.7832 *
  iter   3  loss=  859.16  P=0.8222  R=0.8409  F1=0.8315 *
  iter   4  loss=  711.74  P=0.8069  R=0.8545  F1=0.8300
  iter   5  loss=  557.66  P=0.8472  R=0.8818  F1=0.8641 *
  iter   6  loss=  540.36  P=0.8240  R=0.8727  F1=0.8477
  iter   7  loss=  474.87  P=0.8468  R=0.9045  F1=0.8747 *
  iter   8  loss=  421.69  P=0.8596  R=0.8909  F1=0.8750 *
  iter   9  loss=  371.18  P=0.8369  R=0.8864  F1=0.8609
  iter  10  loss=  333.61  P=0.8455  R=0.8955  F1=0.8698
  iter  11  loss=  320.23  P=0.8734  R=0.9091  F1=0.8909 *
  iter  12  loss=  272.53  P=0.8522  R=0.8909  F1=0.8711
  iter  13  loss=  239.51  P=0.8658  R=0.9091  F1=0.8869
  iter  14  loss=  217.76  P=0.8904  R=0.9227  F1=0.9062 *
  iter  15  loss=  170.71  P=0.8435  R=0.8818  F1=0.8622
  iter  16  loss=  170.46  P=0.8522  R=0.8909  F1=0.8711
  iter  17  loss=  145.42  P=0.8767  R=0.9045  F1=0.8904
  iter  18  loss=  187.19  P=0.8664  R=0.9136  F1=0.8894
  iter  19  loss=  151.39  P=0.8498  R=0.9000  F1=0.8742
  iter  20  loss=  120.25  P=0.8761  R=0.9000  F1=0.8879
  iter  21  loss=  131.66  P=0.8541  R=0.9045  F1=0.8786
  iter  22  loss=  116.34  P=0.8728  R=0.9045  F1=0.8884
  iter  23  loss=  118.29  P=0.8584  R=0.8818  F1=0.8700
  iter  24  loss=   96.43  P=0.8690  R=0.9045  F1=0.8864
  iter  25  loss=   95.11  P=0.8717  R=0.8955  F1=0.8834
  iter  26  loss=  107.57  P=0.8772  R=0.9091  F1=0.8929
  iter  27  loss=   87.30  P=0.8734  R=0.9091  F1=0.8909
  iter  28  loss=   83.33  P=0.8690  R=0.9045  F1=0.8864
  iter  29  loss=   78.49  P=0.8553  R=0.8864  F1=0.8705
  iter  30  loss=   86.74  P=0.8528  R=0.8955  F1=0.8736

Best val F1: 0.9062 — model saved to models/cross_val/10_folds/seed_4841762/fold_7/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 968 rows
  932 examples (provided train) (36 skipped, 7 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 107 rows
  107 examples (provided val) (0 skipped, 3 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen-St. Magnus, Zum Fichtenhof 25" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text " <UNK> Ffm.-Höchst, Gartenstrasse 7" with entities "[(7, 11, 'City'), (12, 18, 'Neighborhood'), (20, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stolberg, Eichsfeldstr.98/Aachen-Land" with entities "[(0, 8, 'City'), (10, 23, 'StreetName'), (23, 25, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wereshchaky-Ukraine" with entities "[(0, 11, 'City'), (12, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Halmei-Szatmar/Rumänien" with entities "[(0, 6, 'City'), (7, 14, 'District'), (15, 23, 'Co...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hofheim T., Hölderlin-Str.4 Kreis Main-Taunus" with entities "[(0, 10, 'City'), (12, 26, 'StreetName'), (26, 27,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Gonsenheim Eleonorenstr. 34" with entities "[(0, 5, 'City'), (6, 16, 'Neighborhood'), (17, 30,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "121 Tappan Avenue Belleville 9 N.Y./Kreis USA" with entities "[(0, 3, 'HouseNumber'), (4, 17, 'StreetName'), (18...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Wuppertal-Sudberg, Hintersudberg 27 Reg.Bez. Düsse..." with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (19, 32...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Essen, Hans-Lutherstr.3" with entities "[(0, 5, 'City'), (7, 22, 'StreetName'), (22, 23, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover Göttinger Chaussee 39." with entities "[(0, 8, 'City'), (9, 27, 'StreetName'), (28, 30, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankenthal Konrad-Linkstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Offenbach/MainBieber, Seligenstädterstr.18 1/10" with entities "[(0, 9, 'City'), (14, 20, 'Neighborhood'), (22, 40...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rixdorf (Berlin-Neuköln)" with entities "[(9, 15, 'City'), (16, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Kaiserslautern Klosterstr.18" with entities "[(0, 14, 'City'), (15, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Hermsdorf, Junostr. 7" with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 26,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochester, N.Y./USA., 300 Joseph Ave." with entities "[(0, 9, 'City'), (11, 15, 'State'), (16, 20, 'Coun...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg,39 Sierichstr. 153." with entities "[(0, 7, 'City'), (11, 21, 'StreetName'), (23, 26, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Sdeh Warburg Erif 5 b. Kfar Saba" with entities "[(0, 12, 'City'), (13, 17, 'StreetName'), (18, 21,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main-Fechenheim" with entities "[(0, 14, 'City'), (15, 25, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "St. Johann-Saarbrücken" with entities "[(0, 10, 'Neighborhood'), (11, 22, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Marstetten-Aitrach, Kr. Wangen" with entities "[(0, 10, 'Neighborhood'), (11, 18, 'City'), (24, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1942.11  P=0.6769  R=0.7154  F1=0.6957 *
  iter   2  loss= 1147.77  P=0.8082  R=0.8049  F1=0.8065 *
  iter   3  loss=  820.11  P=0.8016  R=0.8211  F1=0.8112 *
  iter   4  loss=  765.05  P=0.8144  R=0.8740  F1=0.8431 *
  iter   5  loss=  590.23  P=0.8161  R=0.8659  F1=0.8402
  iter   6  loss=  497.56  P=0.8485  R=0.9106  F1=0.8784 *
  iter   7  loss=  432.24  P=0.8378  R=0.8821  F1=0.8594
  iter   8  loss=  409.52  P=0.8327  R=0.8699  F1=0.8509
  iter   9  loss=  381.43  P=0.8643  R=0.9065  F1=0.8849 *
  iter  10  loss=  331.32  P=0.8606  R=0.8780  F1=0.8692
  iter  11  loss=  260.54  P=0.8488  R=0.8902  F1=0.8690
  iter  12  loss=  225.83  P=0.8649  R=0.9106  F1=0.8871 *
  iter  13  loss=  222.24  P=0.8467  R=0.8984  F1=0.8718
  iter  14  loss=  193.38  P=0.8716  R=0.9106  F1=0.8907 *
  iter  15  loss=  200.48  P=0.8550  R=0.9106  F1=0.8819
  iter  16  loss=  183.42  P=0.8889  R=0.9106  F1=0.8996 *
  iter  17  loss=  165.92  P=0.8795  R=0.8902  F1=0.8848
  iter  18  loss=  129.54  P=0.8667  R=0.8984  F1=0.8822
  iter  19  loss=  163.84  P=0.8626  R=0.9187  F1=0.8898
  iter  20  loss=  146.58  P=0.8473  R=0.9024  F1=0.8740
  iter  21  loss=  138.96  P=0.8373  R=0.8577  F1=0.8474
  iter  22  loss=  127.61  P=0.8627  R=0.8943  F1=0.8782
  iter  23  loss=  107.69  P=0.8724  R=0.8618  F1=0.8671
  iter  24  loss=  122.00  P=0.8543  R=0.8577  F1=0.8560
  iter  25  loss=  106.39  P=0.8560  R=0.8943  F1=0.8748
  iter  26  loss=  100.01  P=0.8523  R=0.9146  F1=0.8824
  iter  27  loss=   82.76  P=0.8701  R=0.8984  F1=0.8840
  iter  28  loss=   94.73  P=0.8533  R=0.8984  F1=0.8752
  iter  29  loss=   62.03  P=0.8583  R=0.8862  F1=0.8720
  iter  30  loss=   77.00  P=0.8696  R=0.8943  F1=0.8818

Best val F1: 0.8996 — model saved to models/cross_val/10_folds/seed_4841762/fold_8/ner_bzk
Loading base model: de_core_news_sm
Loading training data...
  Using provided training DataFrame with 968 rows
  934 examples (provided train) (34 skipped, 8 entity values not aligned)
Loading validation data...
  Using provided validation DataFrame with 107 rows
  105 examples (provided val) (2 skipped, 2 entity values not aligned)

Training for 30 iterations (dropout=0.3)...
  Freezing pipes: ['tok2vec', 'tagger', 'morphologizer', 'parser', 'lemmatizer', 'attribute_ruler']

  0%|          | 0/30 [00:00<?, ?it/s]

/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Frankfurt/Main, Sellerstr.30/Frankfurt/Main (Hesse..." with entities "[(0, 14, 'City'), (16, 26, 'StreetName'), (26, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Tel Aviv/Israel. Javnestr: 16." with entities "[(0, 8, 'City'), (9, 15, 'Country'), (17, 25, 'Str...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hannover, Richard-Wagner-Str.22" with entities "[(0, 8, 'City'), (10, 29, 'StreetName'), (29, 31, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "GAN HASCHOMRON Israel" with entities "[(0, 13, 'City'), (15, 21, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Marienfelde, Alt Marienfelde 4" with entities "[(0, 6, 'City'), (7, 18, 'Neighborhood'), (20, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "62-98 Saunders Street, Rego Park L.I.,New York, US..." with entities "[(0, 5, 'HouseNumber'), (6, 21, 'StreetName'), (23...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Drancy/Seine, 22. rue d'Harmonie Frankreich" with entities "[(0, 6, 'City'), (14, 16, 'HouseNumber'), (18, 32,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Freiburg/Br., Günterstalstr. 54." with entities "[(0, 8, 'City'), (9, 12, 'State'), (14, 28, 'Stree...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Gräfelfing b.München, Hartnagelstr.1/I" with entities "[(0, 10, 'Neighborhood'), (13, 20, 'City'), (22, 3...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mindelheim, Bahnhofstr.14, Krs. Schwaben." with entities "[(0, 10, 'City'), (12, 23, 'StreetName'), (23, 25,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Strafanstalt Straubing Äussere Passauerstr.26" with entities "[(13, 22, 'City'), (23, 43, 'StreetName'), (43, 45...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Schüttorf Kreis-Bentheim" with entities "[(0, 9, 'City'), (16, 24, 'District')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hbg-Bergedorf" with entities "[(4, 13, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Goslar. Jakobistr.36" with entities "[(0, 7, 'City'), (8, 18, 'StreetName'), (18, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen-St. Magnus, Zum Fichtenhof 25" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremerhaven-M., Langemarckstr. 28" with entities "[(0, 11, 'City'), (16, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Lichterfelde-Ost, Berlinerstr.48a (Altershe..." with entities "[(0, 6, 'City'), (7, 23, 'Neighborhood'), (25, 37,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Nordheim/Krs. Heilbronn/N, Kelterstr. 37." with entities "[(0, 8, 'City'), (14, 23, 'District'), (27, 37, 'S...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Neukölln, Sonnenallee 18 b./Wegner" with entities "[(0, 6, 'City'), (7, 15, 'Neighborhood'), (17, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem, Alfasistr.7" with entities "[(0, 9, 'City'), (11, 21, 'StreetName'), (21, 22, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rochest N.Y./USA., 1441 Monroe Avenue" with entities "[(0, 7, 'City'), (8, 12, 'State'), (13, 16, 'Count...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg-Altona" with entities "[(0, 7, 'City'), (8, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "München 15, Herzog Heinrichstr.30/III" with entities "[(0, 7, 'City'), (12, 31, 'StreetName'), (31, 33, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Fischerhüttenstr. 57" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Stuttgart-Bad Cannstatt" with entities "[(0, 9, 'City'), (10, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jerusalem-Rehavia - Israel" with entities "[(0, 9, 'City'), (10, 17, 'Neighborhood'), (20, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Remscheid-Lennep, Ringstr. 123 / Kreis Remscheid" with entities "[(0, 9, 'City'), (10, 16, 'Neighborhood'), (18, 26...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Warsaw-Polen" with entities "[(0, 6, 'City'), (7, 12, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Köln-Dünnwald, Prämonstratenserstr. 72 Köln" with entities "[(0, 4, 'City'), (5, 13, 'Neighborhood'), (15, 35,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Jaffa/Israel Reh 206 Nr. 6" with entities "[(0, 5, 'City'), (6, 12, 'Country'), (19, 20, 'Hou...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bremen, Klitzenburg7(Gröp.)" with entities "[(0, 6, 'City'), (8, 19, 'StreetName'), (19, 20, '...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg 19 Osterstr. 22." with entities "[(0, 7, 'City'), (11, 20, 'StreetName'), (21, 23, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Zehlendorf, Teichstr.9" with entities "[(0, 6, 'City'), (7, 17, 'Neighborhood'), (19, 28,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hagen-Haspe" with entities "[(0, 5, 'City'), (6, 11, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Bohnsdorf, b Berlin-Grünau" with entities "[(0, 9, 'Neighborhood'), (13, 19, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Hamburg,39 Sierichstr. 153." with entities "[(0, 7, 'City'), (11, 21, 'StreetName'), (23, 26, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Berlin-Tempelhof, Friedrich Karlstr. 49 bei Trabbe..." with entities "[(0, 6, 'City'), (7, 16, 'Neighborhood'), (18, 36,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Weiden/Opf. Von Steubenstr.11" with entities "[(0, 11, 'City'), (12, 27, 'StreetName'), (27, 29,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Haspe-Hagen" with entities "[(0, 5, 'Neighborhood'), (6, 11, 'City')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Maria Nostra-Ungarn" with entities "[(0, 12, 'City'), (13, 19, 'Country')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Mainz-Weisenau" with entities "[(0, 5, 'City'), (6, 14, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "20 Orchideenstieg 9." with entities "[(3, 17, 'StreetName'), (18, 19, 'HouseNumber')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Friesenheim/Baden, Friedenstr. 22." with entities "[(0, 11, 'City'), (19, 30, 'StreetName'), (31, 33,...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
/home/rpatroni/bzk-post-processing/.venv/lib/python3.12/site-packages/spacy/training/iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Rixdorf (Berlin-Neuköln)" with entities "[(9, 15, 'City'), (16, 23, 'Neighborhood')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

  iter   1  loss= 1952.08  P=0.7459  R=0.6389  F1=0.6883 *
  iter   2  loss= 1154.19  P=0.8054  R=0.8241  F1=0.8146 *
  iter   3  loss=  900.21  P=0.8394  R=0.8472  F1=0.8433 *
  iter   4  loss=  721.05  P=0.8786  R=0.8380  F1=0.8578 *
  iter   5  loss=  606.93  P=0.8500  R=0.8657  F1=0.8578
  iter   6  loss=  540.89  P=0.8475  R=0.8750  F1=0.8610 *
  iter   7  loss=  450.95  P=0.8894  R=0.8935  F1=0.8915 *
  iter   8  loss=  410.37  P=0.8935  R=0.8935  F1=0.8935 *
  iter   9  loss=  397.97  P=0.8818  R=0.8981  F1=0.8899
  iter  10  loss=  336.43  P=0.8682  R=0.8843  F1=0.8761
  iter  11  loss=  334.87  P=0.8818  R=0.8981  F1=0.8899
  iter  12  loss=  263.01  P=0.8802  R=0.8843  F1=0.8822
  iter  13  loss=  192.77  P=0.8750  R=0.8750  F1=0.8750
  iter  14  loss=  202.46  P=0.8879  R=0.8796  F1=0.8837
  iter  15  loss=  169.32  P=0.8824  R=0.9028  F1=0.8924
  iter  16  loss=  168.99  P=0.8778  R=0.8981  F1=0.8879
  iter  17  loss=  153.24  P=0.8705  R=0.9028  F1=0.8864
  iter  18  loss=  144.30  P=0.8910  R=0.8704  F1=0.8806
  iter  19  loss=  122.80  P=0.8853  R=0.8935  F1=0.8894
  iter  20  loss=  149.52  P=0.8909  R=0.9074  F1=0.8991 *
  iter  21  loss=  114.14  P=0.8977  R=0.8935  F1=0.8956
  iter  22  loss=  111.97  P=0.8909  R=0.9074  F1=0.8991
  iter  23  loss=  151.11  P=0.9078  R=0.9120  F1=0.9099 *
  iter  24  loss=  109.01  P=0.8955  R=0.9120  F1=0.9037
  iter  25  loss=   93.66  P=0.8778  R=0.8981  F1=0.8879
  iter  26  loss=   96.44  P=0.8869  R=0.9074  F1=0.8970
  iter  27  loss=   87.96  P=0.8744  R=0.8704  F1=0.8724
  iter  28  loss=   82.40  P=0.8813  R=0.8935  F1=0.8874
  iter  29  loss=   81.04  P=0.8904  R=0.9028  F1=0.8966
  iter  30  loss=   86.08  P=0.8750  R=0.9074  F1=0.8909

Best val F1: 0.9099 — model saved to models/cross_val/10_folds/seed_4841762/fold_9/ner_bzk