# Disambiguation parameter optimization

> **Notebook convention:** as in [`entity_linking.ipynb`](entity_linking.ipynb), keep this notebook
> limited to function calls and variable definitions (experiment parameters, calls whose results are
> displayed). Every function, class and significant chunk of logic belongs in the support script
> [`disambiguation_optimization_utils.py`](disambiguation_optimization_utils.py), taking its
> dependencies as explicit arguments rather than reading notebook globals.

Explores the parameters of the disambiguation procedure ([`modules/geo_disambiguation.py`](modules/geo_disambiguation.py)),
scored on the **training split only** (`card_id` starting with `train_`).

**Objective**, in order of priority:
1. higher precision;
2. more correctly linked addresses;
3. fewer incorrectly linked addresses (wrong links that are not an ancestor of the true location).

**Method.** The GeoDB search does not depend on the disambiguator, so the training addresses are linked once
by the production pipeline, keeping the addresses the search returned (cached under `cache/`). Every
configuration then only replays the disambiguation of those addresses, in parallel worker processes.

**Stages.** Each stage starts from the best configuration of the previous one:
1. the weights of the weighted score;
2. the parent/child distance thresholds of the hierarchical likelihood;
3. the minimum population for the population order of magnitude;
4. the significance thresholds, keeping the production order;
5. the order of the disambiguation factors, by a greedy search, with the thresholds of stage 4;
6. the order, by moving each factor of the production order up (from the best of stage 4).

`%autoreload` is enabled below, but the evaluation workers load the support script when they start:
rerun the cell creating the `evaluator` after editing it.

In [1]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import entity_linking_notebook_utils as utils
utils.setup_logging()
import disambiguation_optimization_utils as opt
import modules.entity_linking as entity_linking

In [2]:
SEARCH_INDEX_DIR = ".geo_db_search_index"
PARSED_ADDRESSES_CACHE_PATH = Path("experiments_data/entity_linking/parsed_addresses.jsonl")
# The training addresses as the GeoDB search returned them; rebuild after changing the search or the parsing
SEARCHED_FIELDS_CACHE_PATH = Path("cache/disambiguation_optimization/searched_train_fields.pkl")
OVERWRITE_SEARCH_CACHE = False
NUM_SEARCH_WORKERS = utils.default_num_workers()
# Each evaluation worker holds every searched training address (a few hundred MB)
NUM_EVALUATION_WORKERS = 32
# Addresses per evaluation task: small enough for a single configuration to keep every worker busy
EVALUATION_CHUNK_SIZE = 25

In [3]:
ground_truth = utils.load_ground_truth("open_data/bzkopen_linking_groundtruth.jsonl")
parsed_addresses = await utils.load_or_build_parsed_addresses(ground_truth, PARSED_ADDRESSES_CACHE_PATH)
train_rows, train_ground_truth = opt.train_split(parsed_addresses, ground_truth)
print(f"Training addresses: {len(train_rows)} of {len(ground_truth)}")

Running regex parsing on 1090 addresses...
606/1090 addresses need the LLM fallback (regex left them un/partially parsed).
Retrieving cached parsed addresses from experiments_data/entity_linking/parsed_addresses.jsonl...
Training addresses: 771 of 1090

In [4]:
searched_fields = opt.load_or_search_fields(
    train_rows, SEARCHED_FIELDS_CACHE_PATH, f"{SEARCH_INDEX_DIR}/tantivy_index", NUM_SEARCH_WORKERS,
    overwrite=OVERWRITE_SEARCH_CACHE,
)

Retrieving cached searched addresses from cache/disambiguation_optimization/searched_train_fields.pkl...

## Production configuration

The configuration `entity_linking.build_disambiguator()` builds. Replaying its disambiguation must link every
training address as the pipeline did when searching.

In [5]:
opt.cleanup_previous_run(globals()) # Allow script rerunning
production_config = opt.DisambiguationConfig.of(entity_linking.build_disambiguator())
evaluator = opt.ConfigEvaluator(
    SEARCHED_FIELDS_CACHE_PATH, train_ground_truth, NUM_EVALUATION_WORKERS, EVALUATION_CHUNK_SIZE)
opt.check_replay(evaluator, production_config, searched_fields)
evaluator.evaluate({"production": production_config})

2026-10-12 12:31:27.376 INFO     entity_linking.Disambiguator geo_disambiguation.py:399 Initialized with significance thresholds defaultdict(<function _default_significance_threshold at 0x7f6272508b80>, {'fuzzy_similarity_score': 0, 'population_order_of_magnitude': 1, 'weighted_score': 0.05, 'child_parent_likelihood': 0.05, 'entity_types_matching_preferred': 0.05, 'country_likelihood_rank': 0.05, 'phonetic_score': 0.05, 'entity_types_matching': 0.05, 'is_preferred_name': 0.05, 'population_count': 0.05}), primary priority ['weighted_score', 'child_parent_likelihood', 'population_order_of_magnitude', 'fuzzy_similarity_score', 'entity_types_matching_preferred', 'country_likelihood_rank', 'phonetic_score', 'entity_types_matching', 'is_preferred_name', 'population_count'], secondary priority [], population rounding factor 1, min population order of magnitude 100000, score prune thresholds {'fuzzy_similarity_score': 0.4, 'child_parent_likelihood': 0.4}, geo db geo.duckdb, geometry parent/child max distance 50 km, parent/child max distance by admin level {0: 100, 1: 100, 2: 34, 3: 14, 4: 6, 5: 5} km

Evaluating 1 configurations:   0%|          | 0/31 [00:00<?, ?it/s]

Replaying the disambiguation links all 771 addresses as the pipeline did

,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
production,0.879679,658,78,12,6,0.932011,0.990964

In [6]:
print(opt.describe_config(production_config))

# modules/geo_disambiguation.py
DISAMBIGUATION_FACTOR_PRIMARY_PRIORITY = [
    'weighted_score',
    'child_parent_likelihood',
    'population_order_of_magnitude',
    'fuzzy_similarity_score',
    'entity_types_matching_preferred',
    'country_likelihood_rank',
    'phonetic_score',
    'entity_types_matching',
    'is_preferred_name',
    'population_count',
]
DISAMBIGUATION_FACTOR_SECONDARY_PRIORITY = [
]
WEIGHTED_DISAMBIGUATION_FACTORS = {
    'phonetic_score': 2,
    'fuzzy_similarity_score': 3,
    'entity_types_matching_preferred': 1,
}
PARENT_CHILD_MAX_DISTANCE_KM_BY_ADMIN_LEVEL = {
    0: 100,
    1: 100,
    2: 34,
    3: 14,
    4: 6,
    5: 5,
}
# Disambiguator(min_population_order_of_magnitude=...)
min_population_order_of_magnitude = 100_000
# modules/entity_linking.py
SIGNIFICANCE_THRESHOLDS = {
    'weighted_score': 0.05,
    'child_parent_likelihood': 0.05,
    'population_order_of_magnitude': 1,
    'fuzzy_similarity_score': 0,
    'entity_types_matching_preferred': 0.05,
    'country_likelihood_rank': 0.05,
    'phonetic_score': 0.05,
    'entity_types_matching': 0.05,
    'is_preferred_name': 0.05,
    'population_count': 0.05,
}

In [7]:
base_config = production_config.replace(
    primary_priority = production_config.primary_priority + production_config.secondary_priority,
    secondary_priority = tuple()
)
evaluator.evaluate({"base": production_config})

,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
base,0.879679,658,78,12,6,0.932011,0.990964

## Stage 1: weights of the weighted score

The same four factors as the production weights. Round 1 sets every weight to 1 and tries a weight of 2 for each
factor in turn. Round 2 gives the factor that did best at 2 a weight of 3, and tries the other factors at 2 except
one, which weighs 1 or is excluded in turn; plus the other factors all at 2, and all at 1. The production weights
and all weights at 1 are evaluated as well. The best configuration of round 2 is the best overall, since round 2
includes the best of round 1.

In [8]:
weights_round_1, weights_round_2 = opt.optimize_score_weights(
    evaluator, base_config, 
    factors = ["phonetic_score", "fuzzy_similarity_score", "entity_types_matching_preferred", "child_parent_likelihood"])
weights_round_1.evaluations

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

Evaluating 8 configurations:   0%|          | 0/248 [00:00<?, ?it/s]

Best factor weighing 2 in round 1: fuzzy_similarity_score

,phonetic_score,fuzzy_similarity_score,entity_types_matching_preferred,child_parent_likelihood,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
current,2,3,1,NaN,0.879679,658,78,12,6,0.932011,0.990964
"phonetic_score=1, fuzzy_similarity_score=2, entity_types_matching_preferred=1, child_parent_likelihood=1",1,2,1,1.0,0.874499,655,82,12,5,0.929737,0.992424
"phonetic_score=1, fuzzy_similarity_score=1, entity_types_matching_preferred=1, child_parent_likelihood=1",1,1,1,1.0,0.870494,652,85,12,5,0.927454,0.992390
"phonetic_score=2, fuzzy_similarity_score=1, entity_types_matching_preferred=1, child_parent_likelihood=1",2,1,1,1.0,0.870494,652,85,12,5,0.927454,0.992390
"phonetic_score=1, fuzzy_similarity_score=1, entity_types_matching_preferred=2, child_parent_likelihood=1",1,1,2,1.0,0.865154,648,89,12,5,0.924394,0.992343
"phonetic_score=1, fuzzy_similarity_score=1, entity_types_matching_preferred=1, child_parent_likelihood=2",1,1,1,2.0,0.863818,647,90,12,5,0.923626,0.992331

In [9]:
weights_round_2.evaluations

,phonetic_score,fuzzy_similarity_score,entity_types_matching_preferred,child_parent_likelihood,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
current,2,3,1,NaN,0.879679,658,78,12,6,0.932011,0.990964
"phonetic_score=1, fuzzy_similarity_score=3, entity_types_matching_preferred=1, child_parent_likelihood=1",1,3,1,1.0,0.877170,657,79,13,5,0.931254,0.992447
"phonetic_score=2, fuzzy_similarity_score=3, entity_types_matching_preferred=2, child_parent_likelihood=1",2,3,2,1.0,0.875834,656,81,12,5,0.930496,0.992436
"phonetic_score=2, fuzzy_similarity_score=3, entity_types_matching_preferred=2, child_parent_likelihood=0",2,3,2,0.0,0.875668,655,81,12,6,0.929737,0.990923
"phonetic_score=2, fuzzy_similarity_score=3, entity_types_matching_preferred=1, child_parent_likelihood=2",2,3,1,2.0,0.874499,655,83,11,5,0.929737,0.992424
"phonetic_score=2, fuzzy_similarity_score=3, entity_types_matching_preferred=2, child_parent_likelihood=2",2,3,2,2.0,0.871829,653,84,12,5,0.928216,0.992401
"phonetic_score=1, fuzzy_similarity_score=1, entity_types_matching_preferred=1, child_parent_likelihood=1",1,1,1,1.0,0.870494,652,85,12,5,0.927454,0.992390
"phonetic_score=1, fuzzy_similarity_score=3, entity_types_matching_preferred=2, child_parent_likelihood=2",1,3,2,2.0,0.869159,651,86,12,5,0.926690,0.992378
"phonetic_score=0, fuzzy_similarity_score=3, entity_types_matching_preferred=2, child_parent_likelihood=2",0,3,2,2.0,0.865154,648,89,12,5,0.924394,0.992343
"phonetic_score=2, fuzzy_similarity_score=3, entity_types_matching_preferred=0, child_parent_likelihood=2",2,3,0,2.0,0.859813,644,85,20,5,0.921316,0.992296

In [10]:
after_weights = weights_round_2.best_config
print(f"Best weights: {after_weights.score_weights}")

Best weights: {'phonetic_score': 2, 'fuzzy_similarity_score': 3, 'entity_types_matching_preferred': 1}

## Stage 2: distance thresholds of the hierarchical likelihood

Distance from a parent beyond which a child is considered outside it, by the parent's admin level
(`PARENT_CHILD_MAX_DISTANCE_KM_BY_ADMIN_LEVEL`). The production cascade is scaled so that the first threshold
(a region or a state) is each of the distances below, keeping the ratios between levels.

In [11]:
FIRST_DISTANCES_KM = [100, 200, 300, 400, 500]
distances = opt.optimize_parent_child_distances(evaluator, after_weights, FIRST_DISTANCES_KM)
distances.evaluations

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

,admin level 0 (km),admin level 1 (km),admin level 2 (km),admin level 3 (km),admin level 4 (km),admin level 5 (km),precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
200 / 200 / 68 / 28 / 12 / 10,200,200,68,28,12,10,0.882353,660,77,11,6,0.933522,0.990991
300 / 300 / 102 / 42 / 18 / 15,300,300,102,42,18,15,0.881016,659,77,12,6,0.932767,0.990977
100 / 100 / 34 / 14 / 6 / 5,100,100,34,14,6,5,0.879679,658,78,12,6,0.932011,0.990964
400 / 400 / 136 / 56 / 24 / 20,400,400,136,56,24,20,0.879679,658,79,11,6,0.932011,0.990964
500 / 500 / 170 / 70 / 30 / 25,500,500,170,70,30,25,0.878505,658,80,11,5,0.932011,0.992459

In [12]:
after_distances = distances.best_config
print(f"Best distances: {after_distances.parent_child_max_distance_km_by_admin_level}")

Best distances: {0: 200, 1: 200, 2: 68, 3: 28, 4: 12, 5: 10}

## Stage 3: minimum population for the population order of magnitude

Population under which `population_order_of_magnitude` is 0.

In [13]:
MIN_POPULATIONS = [0, 100, 1_000, 10_000, 100_000, 500_000, 1_000_000]
population = opt.optimize_min_population_order_of_magnitude(evaluator, after_distances, MIN_POPULATIONS)
population.evaluations

Evaluating 6 configurations:   0%|          | 0/186 [00:00<?, ?it/s]

,min_population_order_of_magnitude,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
100_000,100000,0.882353,660,77,11,6,0.933522,0.990991
1_000,1000,0.878342,657,84,7,6,0.931254,0.990950
500_000,500000,0.877005,656,78,14,6,0.930496,0.990937
1_000_000,1000000,0.877005,656,78,14,6,0.930496,0.990937
10_000,10000,0.877005,656,83,9,6,0.930496,0.990937
100,100,0.870321,651,90,7,6,0.926690,0.990868
0,0,0.868984,650,91,7,6,0.925926,0.990854

In [14]:
after_population = population.best_config
print(f"Best min population: {after_population.min_population_order_of_magnitude:_}")

Best min population: 100_000

## Stage 4: significance thresholds, in the production order

Keeps the production order of the factors (primary, then secondary) and the best configuration of stage 3. Greedily,
from the first factor to the last, each factor tries its 5 threshold candidates below, with the thresholds
already chosen for the factors before it. The factor's current threshold (0.05 in production) is tried too, and
kept among ties.

Each factor gets 5 threshold candidates suited to the range of its address-level score (an average over the
address' entities):
- scores between 0 and 1 (`weighted_score`, `fuzzy_similarity_score`, `phonetic_score`): fine steps around the production 0.05;
- `child_parent_likelihood` and the entity type matches: coarser steps, since per-entity values are few
  (e.g. 0, 0.25, 0.75, 1) or are ratios of admin codes;
- `is_preferred_name`: 0 or 1 per entity;
- `country_likelihood_rank`: 0 to 3 per entity;
- `population_order_of_magnitude`: 0 or the rounded log10 of the population (about 2 to 7);
- `population_count`: the raw population (`DISAMBIGUATION_POPULATION_ROUNDING_FACTOR` is 1).

In [15]:
SIGNIFICANCE_THRESHOLD_CANDIDATES = {
    # in the production priority order, which breaks ties between orders
    "weighted_score": [0, 0.025, 0.05, 0.1, 0.2],
    "child_parent_likelihood": [0, 0.05, 0.1, 0.2, 0.3],
    "fuzzy_similarity_score": [0, 0.025, 0.05, 0.1, 0.2],
    "entity_types_matching_preferred": [0, 0.05, 0.1, 0.2, 0.3],
    "population_order_of_magnitude": [0, 0.25, 0.5, 1, 2],
    "country_likelihood_rank": [0, 0.25, 0.5, 1, 1.5],
    "phonetic_score": [0, 0.025, 0.05, 0.1, 0.2],
    "entity_types_matching": [0, 0.05, 0.1, 0.2, 0.3],
    "is_preferred_name": [0, 0.1, 0.25, 0.5, 0.75],
    "population_count": [0, 1_000, 10_000, 100_000, 1_000_000],
}

In [16]:
threshold_search = opt.optimize_significance_thresholds(evaluator, after_population, SIGNIFICANCE_THRESHOLD_CANDIDATES)
threshold_search.summary

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

weighted_score: 0.05 -> 0.05

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

child_parent_likelihood: 0.05 -> 0.05

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

population_order_of_magnitude: 1 -> 1

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

fuzzy_similarity_score: 0 -> 0

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

entity_types_matching_preferred: 0.05 -> 0.05

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

country_likelihood_rank: 0.05 -> 0.05

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

phonetic_score: 0.05 -> 0.05

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

entity_types_matching: 0.05 -> 0.05

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

is_preferred_name: 0.05 -> 0.05

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

population_count: 0.05 -> 0.05

,previous threshold,threshold,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
factor,,,,,,,,,
weighted_score,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
child_parent_likelihood,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
population_order_of_magnitude,1.00,1.00,0.882353,660,77,11,6,0.933522,0.990991
fuzzy_similarity_score,0.00,0.00,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching_preferred,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
country_likelihood_rank,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
phonetic_score,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991
population_count,0.05,0.05,0.882353,660,77,11,6,0.933522,0.990991

In [17]:
opt.display_sequential_steps(threshold_search)

**weighted_score**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
weighted_score = 0.05,0.050,True,0.882353,660,77,11,6,0.933522,0.990991
weighted_score = 0.025,0.025,False,0.866131,647,88,12,7,0.923626,0.989297
weighted_score = 0,0.000,False,0.862115,644,90,13,7,0.921316,0.989247
weighted_score = 0.1,0.100,False,0.858289,642,87,19,6,0.919771,0.990741
weighted_score = 0.2,0.200,False,0.850267,636,93,19,6,0.915108,0.990654

**child_parent_likelihood**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
child_parent_likelihood = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
child_parent_likelihood = 0,0.00,False,0.877005,656,81,11,6,0.930496,0.990937
child_parent_likelihood = 0.1,0.10,False,0.872995,653,83,12,6,0.928216,0.990895
child_parent_likelihood = 0.2,0.20,False,0.866310,648,87,13,6,0.924394,0.990826
child_parent_likelihood = 0.3,0.30,False,0.862299,645,90,13,6,0.922087,0.990783

**population_order_of_magnitude**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
population_order_of_magnitude = 1,1.00,True,0.882353,660,77,11,6,0.933522,0.990991
population_order_of_magnitude = 0.5,0.50,False,0.882353,660,77,11,6,0.933522,0.990991
population_order_of_magnitude = 2,2.00,False,0.882353,660,77,11,6,0.933522,0.990991
population_order_of_magnitude = 0,0.00,False,0.881016,659,78,11,6,0.932767,0.990977
population_order_of_magnitude = 0.25,0.25,False,0.881016,659,78,11,6,0.932767,0.990977

**fuzzy_similarity_score**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
fuzzy_similarity_score = 0,0.000,True,0.882353,660,77,11,6,0.933522,0.990991
fuzzy_similarity_score = 0.025,0.025,False,0.880857,658,78,11,7,0.932011,0.989474
fuzzy_similarity_score = 0.05,0.050,False,0.878179,656,81,10,7,0.930496,0.989442
fuzzy_similarity_score = 0.1,0.100,False,0.871486,651,86,10,7,0.926690,0.989362
fuzzy_similarity_score = 0.2,0.200,False,0.870147,650,87,10,7,0.925926,0.989346

**entity_types_matching_preferred**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching_preferred = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching_preferred = 0,0.00,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching_preferred = 0.1,0.10,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching_preferred = 0.2,0.20,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching_preferred = 0.3,0.30,False,0.882353,660,77,11,6,0.933522,0.990991

**country_likelihood_rank**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
country_likelihood_rank = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
country_likelihood_rank = 0,0.00,False,0.882353,660,77,11,6,0.933522,0.990991
country_likelihood_rank = 0.25,0.25,False,0.882353,660,77,11,6,0.933522,0.990991
country_likelihood_rank = 0.5,0.50,False,0.881016,659,78,11,6,0.932767,0.990977
country_likelihood_rank = 1,1.00,False,0.875668,655,84,9,6,0.929737,0.990923
country_likelihood_rank = 1.5,1.50,False,0.875668,655,84,9,6,0.929737,0.990923

**phonetic_score**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
phonetic_score = 0.05,0.050,True,0.882353,660,77,11,6,0.933522,0.990991
phonetic_score = 0.025,0.025,False,0.882353,660,77,11,6,0.933522,0.990991
phonetic_score = 0.1,0.100,False,0.882353,660,77,11,6,0.933522,0.990991
phonetic_score = 0,0.000,False,0.881016,659,77,12,6,0.932767,0.990977
phonetic_score = 0.2,0.200,False,0.881016,659,78,11,6,0.932767,0.990977

**entity_types_matching**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching = 0,0.00,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching = 0.1,0.10,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching = 0.2,0.20,False,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching = 0.3,0.30,False,0.882353,660,77,11,6,0.933522,0.990991

**is_preferred_name**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
is_preferred_name = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name = 0,0.00,False,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name = 0.1,0.10,False,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name = 0.25,0.25,False,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name = 0.5,0.50,False,0.879679,658,79,11,6,0.932011,0.990964
is_preferred_name = 0.75,0.75,False,0.879679,658,79,11,6,0.932011,0.990964

**population_count**

,threshold,current,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
population_count = 0.05,0.05,True,0.882353,660,77,11,6,0.933522,0.990991
population_count = 0,0.00,False,0.882353,660,77,11,6,0.933522,0.990991
population_count = 1000,1000.00,False,0.881016,659,77,12,6,0.932767,0.990977
population_count = 10000,10000.00,False,0.881016,659,77,12,6,0.932767,0.990977
population_count = 100000,100000.00,False,0.881016,659,77,12,6,0.932767,0.990977
population_count = 1e+06,1000000.00,False,0.881016,659,77,12,6,0.932767,0.990977

In [18]:
after_thresholds = threshold_search.best_config

## Stage 5: order of the factors, by a greedy search

Which factor alone decides best? With that one set, which factor decides best after it? This repeats until all
10 factors are ordered. Each factor keeps its significance threshold from stage 4.

The ordered factors are all primary factors: candidates no factor tells apart by its threshold are compared
again on the same factors with no threshold (see `geo_disambiguation.comparison_steps`); there are no
secondary factors.

In [19]:
order_search = opt.greedy_order_search(evaluator, after_thresholds, SIGNIFICANCE_THRESHOLD_CANDIDATES)
order_search.summary

Evaluating 10 configurations:   0%|          | 0/310 [00:00<?, ?it/s]

Step: entity_types_matching (0.05)

Evaluating 9 configurations:   0%|          | 0/279 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05)

Evaluating 8 configurations:   0%|          | 0/248 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1)

Evaluating 7 configurations:   0%|          | 0/217 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0)

Evaluating 6 configurations:   0%|          | 0/186 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05)

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05)

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05)

Evaluating 3 configurations:   0%|          | 0/93 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05)

Evaluating 2 configurations:   0%|          | 0/62 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05) > country_likelihood_rank (0.05)

Evaluating 1 configurations:   0%|          | 0/31 [00:00<?, ?it/s]

Step: entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05) > country_likelihood_rank (0.05) > is_preferred_name (0.05)
Best order (step 8): entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05)

,added factor,configurations evaluated,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
step,,,,,,,,,
1,entity_types_matching,10,0.643216,128,22,49,555,0.290249,0.187408
2,entity_types_matching_preferred,9,0.663594,144,25,48,537,0.320713,0.211454
3,population_order_of_magnitude,8,0.739130,374,97,35,248,0.663121,0.601286
4,fuzzy_similarity_score,7,0.759287,511,118,44,81,0.807905,0.863176
5,child_parent_likelihood,6,0.778723,549,110,46,49,0.842671,0.918060
6,population_count,5,0.797587,595,140,11,8,0.882135,0.986733
7,weighted_score,4,0.800268,597,140,9,8,0.883790,0.986777
8,phonetic_score,3,0.800268,597,140,9,8,0.883790,0.986777
9,country_likelihood_rank,2,0.799197,597,140,10,7,0.883790,0.988411
10,is_preferred_name,1,0.798128,597,141,10,6,0.883790,0.990050

In [20]:
opt.display_greedy_steps(order_search, top=5)

**Step 1**: the single best factor

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05),entity_types_matching,0.643216,128,22,49,555,0.290249,0.187408
entity_types_matching_preferred (0.05),entity_types_matching_preferred,0.628440,137,26,55,536,0.307520,0.203566
weighted_score (0.05),weighted_score,0.615230,307,84,108,255,0.578699,0.546263
is_preferred_name (0.05),is_preferred_name,0.565401,134,29,74,517,0.301802,0.205837
fuzzy_similarity_score (0),fuzzy_similarity_score,0.549793,265,64,153,272,0.520118,0.493482

**Step 2**: factor added at position 2

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05),entity_types_matching_preferred,0.663594,144,25,48,537,0.320713,0.211454
entity_types_matching (0.05) > weighted_score (0.05),weighted_score,0.662083,337,99,73,245,0.617782,0.579038
entity_types_matching (0.05) > fuzzy_similarity_score (0),fuzzy_similarity_score,0.608696,294,75,114,271,0.561069,0.520354
entity_types_matching (0.05) > is_preferred_name (0.05),is_preferred_name,0.599174,145,29,68,512,0.322581,0.220700
entity_types_matching (0.05) > population_order_of_magnitude (1),population_order_of_magnitude,0.598425,304,105,99,246,0.574669,0.552727

**Step 3**: factor added at position 3

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1),population_order_of_magnitude,0.739130,374,97,35,248,0.663121,0.601286
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > fuzzy_similarity_score (0),fuzzy_similarity_score,0.686354,337,80,74,263,0.617782,0.561667
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > weighted_score (0.05),weighted_score,0.661417,336,100,72,246,0.616514,0.577320
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > phonetic_score (0.05),phonetic_score,0.653846,289,80,73,312,0.554171,0.480865
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_count (0.05),population_count,0.638441,475,259,10,10,0.772986,0.979381

**Step 4**: factor added at position 4

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0),fuzzy_similarity_score,0.759287,511,118,44,81,0.807905,0.863176
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > weighted_score (0.05),weighted_score,0.747076,511,133,40,70,0.807905,0.879518
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > phonetic_score (0.05),phonetic_score,0.745763,484,119,46,105,0.781906,0.821732
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > is_preferred_name (0.05),is_preferred_name,0.741155,398,99,40,217,0.690972,0.647154
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > child_parent_likelihood (0.05),child_parent_likelihood,0.707071,420,103,71,160,0.715503,0.724138

**Step 5**: factor added at position 5

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05),child_parent_likelihood,0.778723,549,110,46,49,0.842671,0.918060
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > population_count (0.05),population_count,0.770470,574,158,13,9,0.864458,0.984563
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > is_preferred_name (0.05),is_preferred_name,0.755043,524,121,49,60,0.820031,0.897260
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > weighted_score (0.05),weighted_score,0.751825,515,129,41,69,0.811663,0.881849
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > phonetic_score (0.05),phonetic_score,0.751825,515,130,40,69,0.811663,0.881849

**Step 6**: factor added at position 6

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05),population_count,0.797587,595,140,11,8,0.882135,0.986733
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > is_preferred_name (0.05),is_preferred_name,0.779330,558,112,46,38,0.850610,0.936242
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > weighted_score (0.05),weighted_score,0.775281,552,118,42,42,0.845329,0.929293
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > phonetic_score (0.05),phonetic_score,0.775281,552,119,41,42,0.845329,0.929293
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > country_likelihood_rank (0.05),country_likelihood_rank,0.760870,560,116,60,18,0.852359,0.968858

**Step 7**: factor added at position 7

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05),weighted_score,0.800268,597,140,9,8,0.883790,0.986777
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > phonetic_score (0.05),phonetic_score,0.800268,597,140,9,8,0.883790,0.986777
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > country_likelihood_rank (0.05),country_likelihood_rank,0.797587,595,140,11,8,0.882135,0.986733
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > is_preferred_name (0.05),is_preferred_name,0.796519,595,141,11,7,0.882135,0.988372

**Step 8**: factor added at position 8

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05),phonetic_score,0.800268,597,140,9,8,0.88379,0.986777
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > country_likelihood_rank (0.05),country_likelihood_rank,0.799197,597,140,10,7,0.88379,0.988411
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > is_preferred_name (0.05),is_preferred_name,0.799197,597,141,9,7,0.88379,0.988411

**Step 9**: factor added at position 9

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05) > country_likelihood_rank (0.05),country_likelihood_rank,0.799197,597,140,10,7,0.88379,0.988411
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05) > is_preferred_name (0.05),is_preferred_name,0.799197,597,141,9,7,0.88379,0.988411

**Step 10**: factor added at position 10

,added factor,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching (0.05) > entity_types_matching_preferred (0.05) > population_order_of_magnitude (1) > fuzzy_similarity_score (0) > child_parent_likelihood (0.05) > population_count (0.05) > weighted_score (0.05) > phonetic_score (0.05) > country_likelihood_rank (0.05) > is_preferred_name (0.05),is_preferred_name,0.798128,597,141,10,6,0.88379,0.99005

## Stage 6: order, by moving factors up

Starts from the best configuration of stage 4. From the last factor of the production order to the first, each
factor moves up one position at a time while the objective is not worse than at the position before (ties keep
moving it up). It stays at the last position that was not worse. The boundary between primary and secondary
factors stays at the same position: a secondary factor moved above it becomes primary, and the last primary factor
becomes secondary.

In [21]:
order_mutation = opt.move_factors_up(evaluator, after_thresholds)
order_mutation.summary

Evaluating 9 configurations:   0%|          | 0/279 [00:00<?, ?it/s]

population_count: position 10 -> 10

Evaluating 8 configurations:   0%|          | 0/248 [00:00<?, ?it/s]

is_preferred_name: position 9 -> 9

Evaluating 7 configurations:   0%|          | 0/217 [00:00<?, ?it/s]

entity_types_matching: position 8 -> 8

Evaluating 6 configurations:   0%|          | 0/186 [00:00<?, ?it/s]

phonetic_score: position 7 -> 7

Evaluating 5 configurations:   0%|          | 0/155 [00:00<?, ?it/s]

country_likelihood_rank: position 6 -> 6

Evaluating 4 configurations:   0%|          | 0/124 [00:00<?, ?it/s]

entity_types_matching_preferred: position 5 -> 5

Evaluating 3 configurations:   0%|          | 0/93 [00:00<?, ?it/s]

fuzzy_similarity_score: position 4 -> 4

Evaluating 2 configurations:   0%|          | 0/62 [00:00<?, ?it/s]

population_order_of_magnitude: position 3 -> 3

Evaluating 1 configurations:   0%|          | 0/31 [00:00<?, ?it/s]

child_parent_likelihood: position 2 -> 2
weighted_score: position 1 -> 1

,from position,to position,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
factor,,,,,,,,,
population_count,10,10,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
is_preferred_name,9,9,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
entity_types_matching,8,8,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
phonetic_score,7,7,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
country_likelihood_rank,6,6,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
entity_types_matching_preferred,5,5,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
fuzzy_similarity_score,4,4,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
population_order_of_magnitude,3,3,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
child_parent_likelihood,2,2,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991
weighted_score,1,1,0.882353,660.0,77.0,11.0,6.0,0.933522,0.990991

In [22]:
opt.display_sequential_steps(order_mutation)

**population_count**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
population_count at position 9,9,True,0.872995,653,85,10,6,0.928216,0.990895
population_count at position 8,8,False,0.852941,638,103,7,6,0.916667,0.990683
population_count at position 7,7,False,0.852941,638,103,7,6,0.916667,0.990683
population_count at position 6,6,False,0.839572,628,113,7,6,0.908828,0.990536
population_count at position 5,5,False,0.839572,628,113,7,6,0.908828,0.990536
population_count at position 4,4,False,0.827540,619,122,7,6,0.901675,0.990400
population_count at position 3,3,False,0.827540,619,122,7,6,0.901675,0.990400
population_count at position 2,2,False,0.790107,591,150,7,6,0.878810,0.989950
population_count at position 1,1,False,0.538051,403,289,57,5,0.696629,0.987745

**is_preferred_name**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
is_preferred_name at position 8,8,True,0.882353,660,77,11,6,0.933522,0.990991
is_preferred_name at position 7,7,False,0.882195,659,78,10,7,0.932767,0.989489
is_preferred_name at position 6,6,False,0.879518,657,80,10,7,0.931254,0.989458
is_preferred_name at position 5,5,False,0.879518,657,80,10,7,0.931254,0.989458
is_preferred_name at position 4,4,False,0.860590,642,95,9,8,0.919771,0.987692
is_preferred_name at position 3,3,False,0.853691,636,99,10,9,0.915108,0.986047
is_preferred_name at position 2,2,False,0.842953,628,107,10,9,0.908828,0.985871
is_preferred_name at position 1,1,False,0.813423,606,127,12,9,0.891176,0.985366

**entity_types_matching**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching at position 7,7,True,0.882353,660,77,11,6,0.933522,0.990991
entity_types_matching at position 6,6,False,0.878342,657,80,11,6,0.931254,0.990950
entity_types_matching at position 5,5,False,0.878342,657,80,11,6,0.931254,0.990950
entity_types_matching at position 4,4,False,0.878342,657,80,11,6,0.931254,0.990950
entity_types_matching at position 3,3,False,0.876841,655,81,11,7,0.929737,0.989426
entity_types_matching at position 2,2,False,0.875502,654,82,11,7,0.928977,0.989410
entity_types_matching at position 1,1,False,0.852744,637,97,13,7,0.915888,0.989130

**phonetic_score**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
phonetic_score at position 6,6,True,0.881016,659,78,11,6,0.932767,0.990977
phonetic_score at position 5,5,False,0.881016,659,78,11,6,0.932767,0.990977
phonetic_score at position 4,4,False,0.880857,658,78,11,7,0.932011,0.989474
phonetic_score at position 3,3,False,0.875502,654,81,12,7,0.928977,0.989410
phonetic_score at position 2,2,False,0.870147,650,85,12,7,0.925926,0.989346
phonetic_score at position 1,1,False,0.868809,649,86,12,7,0.925160,0.989329

**country_likelihood_rank**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
country_likelihood_rank at position 5,5,True,0.882353,660,77,11,6,0.933522,0.990991
country_likelihood_rank at position 4,4,False,0.878342,657,80,11,6,0.931254,0.990950
country_likelihood_rank at position 3,3,False,0.872995,653,84,11,6,0.928216,0.990895
country_likelihood_rank at position 2,2,False,0.858289,642,95,11,6,0.919771,0.990741
country_likelihood_rank at position 1,1,False,0.786290,585,148,11,10,0.873786,0.983193

**entity_types_matching_preferred**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
entity_types_matching_preferred at position 4,4,True,0.881016,659,78,11,6,0.932767,0.990977
entity_types_matching_preferred at position 3,3,False,0.881016,659,78,11,6,0.932767,0.990977
entity_types_matching_preferred at position 2,2,False,0.879679,658,79,11,6,0.932011,0.990964
entity_types_matching_preferred at position 1,1,False,0.875668,655,81,12,6,0.929737,0.990923

**fuzzy_similarity_score**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
fuzzy_similarity_score at position 3,3,True,0.879679,658,79,11,6,0.932011,0.990964
fuzzy_similarity_score at position 2,2,False,0.877005,656,81,11,6,0.930496,0.990937
fuzzy_similarity_score at position 1,1,False,0.875668,655,82,11,6,0.929737,0.990923

**population_order_of_magnitude**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
population_order_of_magnitude at position 2,2,True,0.878342,657,80,11,6,0.931254,0.990950
population_order_of_magnitude at position 1,1,False,0.802403,601,126,22,5,0.887085,0.991749

**child_parent_likelihood**

,position,worse or same as the position below,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall
child_parent_likelihood at position 1,1,True,0.862483,646,93,10,5,0.922857,0.99232

**weighted_score**

_already first_

In [23]:
after_order_mutation = order_mutation.best_config

## Summary

In [24]:
stage_configs = {
    "production": production_config,
    "base" : base_config,
    "1. weights": after_weights,
    "2. distances": after_distances,
    "3. min population": after_population,
    "4. thresholds": after_thresholds,
    "5. greedy factor order": order_search.best_config,
    "6. moving factors up": after_order_mutation,
}
opt.compare_stages(evaluator, stage_configs)

,precision,correctly_linked,incorrectly_linked,partially_linked,failed_to_link,f1,recall,Δ precision,Δ correctly_linked,Δ incorrectly_linked
production,0.879679,658,78,12,6,0.932011,0.990964,0.000000,0.0,0.0
base,0.879679,658,78,12,6,0.932011,0.990964,0.000000,0.0,0.0
1. weights,0.879679,658,78,12,6,0.932011,0.990964,0.000000,0.0,0.0
2. distances,0.882353,660,77,11,6,0.933522,0.990991,0.002674,2.0,-1.0
3. min population,0.882353,660,77,11,6,0.933522,0.990991,0.002674,2.0,-1.0
4. thresholds,0.882353,660,77,11,6,0.933522,0.990991,0.002674,2.0,-1.0
5. greedy factor order,0.800268,597,140,9,8,0.883790,0.986777,-0.079411,-61.0,62.0
6. moving factors up,0.882353,660,77,11,6,0.933522,0.990991,0.002674,2.0,-1.0

In [25]:
opt.deciding_factor_counts(evaluator, stage_configs)

,production,base,1. weights,2. distances,3. min population,4. thresholds,5. greedy factor order,6. moving factors up
(common parent of tied candidates),9,9,9,8,8,8,6,8
(single candidate),98,98,98,98,98,98,98,98
child_parent_likelihood,82,82,82,90,90,90,31,90
country_likelihood_rank,24,24,24,25,25,25,0,25
entity_types_matching,25,25,25,24,24,24,20,24
entity_types_matching_preferred,0,0,0,0,0,0,18,0
fuzzy_similarity_score,24,24,24,24,24,24,196,24
is_preferred_name,8,8,8,8,8,8,0,8
phonetic_score,3,3,3,2,2,2,1,2
population_count,61,61,61,56,56,56,80,56
population_order_of_magnitude,185,185,185,185,185,185,264,185
weighted_score,198,198,198,197,197,197,1,197

In [26]:
import datetime
print(datetime.datetime.now())
print(opt.describe_config(after_order_mutation))

2026-10-12 12:40:36.968064
# modules/geo_disambiguation.py
DISAMBIGUATION_FACTOR_PRIMARY_PRIORITY = [
    'weighted_score',
    'child_parent_likelihood',
    'population_order_of_magnitude',
    'fuzzy_similarity_score',
    'entity_types_matching_preferred',
    'country_likelihood_rank',
    'phonetic_score',
    'entity_types_matching',
    'is_preferred_name',
    'population_count',
]
DISAMBIGUATION_FACTOR_SECONDARY_PRIORITY = [
]
WEIGHTED_DISAMBIGUATION_FACTORS = {
    'phonetic_score': 2,
    'fuzzy_similarity_score': 3,
    'entity_types_matching_preferred': 1,
}
PARENT_CHILD_MAX_DISTANCE_KM_BY_ADMIN_LEVEL = {
    0: 200,
    1: 200,
    2: 68,
    3: 28,
    4: 12,
    5: 10,
}
# Disambiguator(min_population_order_of_magnitude=...)
min_population_order_of_magnitude = 100_000
# modules/entity_linking.py
SIGNIFICANCE_THRESHOLDS = {
    'weighted_score': 0.05,
    'child_parent_likelihood': 0.05,
    'population_order_of_magnitude': 1,
    'fuzzy_similarity_score': 0,
    'entity_types_matching_preferred': 0.05,
    'country_likelihood_rank': 0.05,
    'phonetic_score': 0.05,
    'entity_types_matching': 0.05,
    'is_preferred_name': 0.05,
    'population_count': 0.05,
}

In [27]:
evaluator.close()