In [1]:
import pandas as pd
import numpy as np

cols = pd.MultiIndex.from_product(
    [["A", "B"], ["x", "y"], ["value", "other"]],
    names=["lvl0", "lvl1", "lvl2"]
)

df = pd.DataFrame(
    np.random.randn(5, len(cols)),
    columns=cols
)

other_df = pd.DataFrame(["q", "w", "e", "r", "t"], columns=["foobar"])

df.loc[0, ("A", "x", "value")] = None
df.loc[1, ("B", "y", "value")] = None

df

lvl0         A                                       B                      \
lvl1         x                   y                   x                   y
lvl2     value     other     value     other     value     other     value
0          NaN  0.605365  0.316627 -0.365692 -0.768940  0.899933 -0.714707
1     1.878808 -1.679979 -0.762629  0.890419  0.748885 -2.120749       NaN
2    -0.555267 -0.475291 -1.704787 -0.417293  0.054613  0.634394 -0.878724
3     0.345691 -1.222493 -0.861591 -1.130675  1.072334 -0.465603 -0.900609
4     0.456413 -1.767559  0.624581 -0.140892 -1.002934 -1.002131  1.077091

lvl0
lvl1
lvl2     other
0    -1.075817
1    -0.139300
2    -1.204453
3    -0.070163
4     0.872640

In [2]:
df.max(axis=1)

0    0.899933
1    1.878808
2    0.634394
3    1.072334
4    1.077091
dtype: float64

In [3]:
out = (
    df
    .xs("value", level=2, axis=1)     # keep only lowest-level column
    .stack([0, 1])                    # move lvl0, lvl1 into rows
    .reset_index()
)
out
out.drop(columns=["I made this up"], errors="ignore")

    level_0 lvl0 lvl1         0
0         0    A    x       NaN
1         0    A    y  0.316627
2         0    B    x -0.768940
3         0    B    y -0.714707
4         1    A    x  1.878808
5         1    A    y -0.762629
6         1    B    x  0.748885
7         1    B    y       NaN
8         2    A    x -0.555267
9         2    A    y -1.704787
10        2    B    x  0.054613
11        2    B    y -0.878724
12        3    A    x  0.345691
13        3    A    y -0.861591
14        3    B    x  1.072334
15        3    B    y -0.900609
16        4    A    x  0.456413
17        4    A    y  0.624581
18        4    B    x -1.002934
19        4    B    y  1.077091

In [4]:
other_df = pd.DataFrame([[f"a{i}", f"b{i}"] for i in range(5)], columns=["A", "B"])
other_df

    A   B
0  a0  b0
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [5]:
s = out.merge(
        other_df
        .stack()
        .reset_index()
        .rename(columns={"level_1" : "lvl0", 0 : "testCol"}),
        on = ["level_0", "lvl0"],
        how="inner"
)
s

    level_0 lvl0 lvl1         0 testCol
0         0    A    x       NaN      a0
1         0    A    y  0.316627      a0
2         0    B    x -0.768940      b0
3         0    B    y -0.714707      b0
4         1    A    x  1.878808      a1
5         1    A    y -0.762629      a1
6         1    B    x  0.748885      b1
7         1    B    y       NaN      b1
8         2    A    x -0.555267      a2
9         2    A    y -1.704787      a2
10        2    B    x  0.054613      b2
11        2    B    y -0.878724      b2
12        3    A    x  0.345691      a3
13        3    A    y -0.861591      a3
14        3    B    x  1.072334      b3
15        3    B    y -0.900609      b3
16        4    A    x  0.456413      a4
17        4    A    y  0.624581      a4
18        4    B    x -1.002934      b4
19        4    B    y  1.077091      b4

In [6]:
pd.DataFrame([[1,2,3],[4,5,6]])

   0  1  2
0  1  2  3
1  4  5  6

In [7]:
import re
CLEANUP_REGEX = re.compile(r"([,.]|\(.*\))")
CLEANUP_REGEX.sub("", "somewhere, in the u.s.a (this is trash)")

'somewhere in the usa '

In [8]:
x = pd.concat({
    "A" : pd.Series([1,2,3], index=["a","b","c"]),
    "B" : pd.Series([4,5,6], index=["d","e","f"])
})
print(type(x))
x

<class 'pandas.Series'>

A  a    1
   b    2
   c    3
B  d    4
   e    5
   f    6
dtype: int64

In [9]:
print(bool(""))

False

In [10]:
from token_classifiers import TokenClassifierAddressParser
model = TokenClassifierAddressParser("hm-haitham/xlm-roberta-large-address-parser")
model.pipeline("123 Main St, Springfield, IL 62704")

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[{'entity_group': 'LABEL_9',
  'score': 0.9934592,
  'word': '123',
  'start': 0,
  'end': 3},
 {'entity_group': 'LABEL_8',
  'score': 0.98392993,
  'word': 'Main',
  'start': 4,
  'end': 8},
 {'entity_group': 'LABEL_17',
  'score': 0.9963374,
  'word': 'St',
  'start': 9,
  'end': 11},
 {'entity_group': 'LABEL_3',
  'score': 0.7324795,
  'word': ', Spring',
  'start': 11,
  'end': 19},
 {'entity_group': 'LABEL_12',
  'score': 0.9188455,
  'word': 'field',
  'start': 19,
  'end': 24},
 {'entity_group': 'LABEL_7',
  'score': 0.9562851,
  'word': ', IL',
  'start': 24,
  'end': 28},
 {'entity_group': 'LABEL_6',
  'score': 0.9865573,
  'word': '6',
  'start': 29,
  'end': 30},
 {'entity_group': 'LABEL_15',
  'score': 0.9232305,
  'word': '2704',
  'start': 30,
  'end': 34}]

In [11]:
model.parse_addresses(["123 Main St, Springfield, IL 62704"])

[{'HouseNumber': '123',
  'StreetName': 'Main St',
  'City': 'Springfield',
  'State': 'IL',
  'PostalCode': '62704'}]

In [12]:
import numpy as np
a = [0.2, 0.5, 0.3]
b = [0.1, 0.6, 0.3]
np.sum(np.array(a) * np.array(b))

0.41000000000000003