In [1]:
import pandas as pd
import numpy as np

cols = pd.MultiIndex.from_product(
    [["A", "B"], ["x", "y"], ["value", "other"]],
    names=["lvl0", "lvl1", "lvl2"]
)

df = pd.DataFrame(
    np.random.randn(5, len(cols)),
    columns=cols
)

other_df = pd.DataFrame(["q", "w", "e", "r", "t"], columns=["foobar"])

df.loc[0, ("A", "x", "value")] = None
df.loc[1, ("B", "y", "value")] = None

df

lvl0         A                                       B                      \
lvl1         x                   y                   x                   y
lvl2     value     other     value     other     value     other     value
0          NaN  1.337524 -1.227112  1.516670 -0.197153  0.598133 -0.525522
1     0.607795  0.301122 -1.173528  0.285103  0.088741 -0.258890       NaN
2    -0.289120 -0.969683 -1.254621 -1.039125 -0.397180  1.332197  1.518788
3    -1.176728 -0.228243  0.388959  0.276513  0.104007  0.520823 -2.157428
4     1.649619  0.525147 -0.905642 -0.121905  0.946906 -0.207627 -0.755677

lvl0
lvl1
lvl2     other
0    -1.638372
1     0.942878
2     1.892599
3     0.516652
4     0.126710

In [2]:
out = (
    df
    .xs("value", level=2, axis=1)     # keep only lowest-level column
    .stack([0, 1])                    # move lvl0, lvl1 into rows
    .reset_index()
)
out
out.drop(columns=["I made this up"], errors="ignore")

    level_0 lvl0 lvl1         0
0         0    A    x       NaN
1         0    A    y -1.227112
2         0    B    x -0.197153
3         0    B    y -0.525522
4         1    A    x  0.607795
5         1    A    y -1.173528
6         1    B    x  0.088741
7         1    B    y       NaN
8         2    A    x -0.289120
9         2    A    y -1.254621
10        2    B    x -0.397180
11        2    B    y  1.518788
12        3    A    x -1.176728
13        3    A    y  0.388959
14        3    B    x  0.104007
15        3    B    y -2.157428
16        4    A    x  1.649619
17        4    A    y -0.905642
18        4    B    x  0.946906
19        4    B    y -0.755677

In [3]:
other_df = pd.DataFrame([[f"a{i}", f"b{i}"] for i in range(5)], columns=["A", "B"])
other_df

    A   B
0  a0  b0
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [4]:
s = out.merge(
        other_df
        .stack()
        .reset_index()
        .rename(columns={"level_1" : "lvl0", 0 : "testCol"}),
        on = ["level_0", "lvl0"],
        how="inner"
)
s

    level_0 lvl0 lvl1         0 testCol
0         0    A    x       NaN      a0
1         0    A    y -1.227112      a0
2         0    B    x -0.197153      b0
3         0    B    y -0.525522      b0
4         1    A    x  0.607795      a1
5         1    A    y -1.173528      a1
6         1    B    x  0.088741      b1
7         1    B    y       NaN      b1
8         2    A    x -0.289120      a2
9         2    A    y -1.254621      a2
10        2    B    x -0.397180      b2
11        2    B    y  1.518788      b2
12        3    A    x -1.176728      a3
13        3    A    y  0.388959      a3
14        3    B    x  0.104007      b3
15        3    B    y -2.157428      b3
16        4    A    x  1.649619      a4
17        4    A    y -0.905642      a4
18        4    B    x  0.946906      b4
19        4    B    y -0.755677      b4

In [5]:
pd.DataFrame([[1,2,3],[4,5,6]])

   0  1  2
0  1  2  3
1  4  5  6

In [6]:
import re
CLEANUP_REGEX = re.compile(r"([,.]|\(.*\))")
CLEANUP_REGEX.sub("", "somewhere, in the u.s.a (this is trash)")

'somewhere in the usa '

In [7]:
x = pd.concat({
    "A" : pd.Series([1,2,3], index=["a","b","c"]),
    "B" : pd.Series([4,5,6], index=["d","e","f"])
})
print(type(x))
x

<class 'pandas.Series'>

A  a    1
   b    2
   c    3
B  d    4
   e    5
   f    6
dtype: int64

In [8]:
print(bool(""))

False

In [1]:
from llm_token_classifiers import TokenClassifierAddressParser
model = TokenClassifierAddressParser("hm-haitham/xlm-roberta-large-address-parser")
model.pipeline("123 Main St, Springfield, IL 62704")

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[{'entity': 'LABEL_9',
  'score': 0.9934592,
  'index': 1,
  'word': '▁123',
  'start': 0,
  'end': 3},
 {'entity': 'LABEL_8',
  'score': 0.98392993,
  'index': 2,
  'word': '▁Main',
  'start': 4,
  'end': 8},
 {'entity': 'LABEL_17',
  'score': 0.9963374,
  'index': 3,
  'word': '▁St',
  'start': 9,
  'end': 11},
 {'entity': 'LABEL_3',
  'score': 0.47186095,
  'index': 4,
  'word': ',',
  'start': 11,
  'end': 12},
 {'entity': 'LABEL_3',
  'score': 0.9930981,
  'index': 5,
  'word': '▁Spring',
  'start': 13,
  'end': 19},
 {'entity': 'LABEL_12',
  'score': 0.9188455,
  'index': 6,
  'word': 'field',
  'start': 19,
  'end': 24},
 {'entity': 'LABEL_7',
  'score': 0.9497917,
  'index': 7,
  'word': ',',
  'start': 24,
  'end': 25},
 {'entity': 'LABEL_7',
  'score': 0.96277845,
  'index': 8,
  'word': '▁IL',
  'start': 26,
  'end': 28},
 {'entity': 'LABEL_6',
  'score': 0.9865573,
  'index': 9,
  'word': '▁6',
  'start': 29,
  'end': 30},
 {'entity': 'LABEL_15',
  'score': 0.85332733,
  'index': 10,
  'word': '27',
  'start': 30,
  'end': 32},
 {'entity': 'LABEL_15',
  'score': 0.9931338,
  'index': 11,
  'word': '04',
  'start': 32,
  'end': 34}]

In [2]:
model.parse_addresses(["123 Main St, Springfield, IL 62704"])

[{'HouseNumber': '123',
  'StreetName': 'Main St',
  'City': ', Springfield',
  'State': ', IL'}]

In [6]:
import numpy as np
a = [0.2, 0.5, 0.3]
b = [0.1, 0.6, 0.3]
np.sum(np.array(a) * np.array(b))

0.41000000000000003